/* M 172 question bank. Calculated questions draw fresh numbers every time; bank items are
   [prompt, correct, [wrong answers], explanation]. Written for Mathub from standard Calculus II
   material and the syllabus topics; not from the instructor. Typed answers accept exact forms
   such as 2pi/15 or e^2-1, and decimals within 0.5%. */
const R = String.raw;
const calc = (topic, o) => Object.assign({ type: 'calc', topic }, o);
const cmc = (topic, o) => Object.assign({ type: 'calc-mc', topic }, o);
const bank = (topic, items, extra = {}) => Object.assign({ type: 'bank', topic, items, options: 4 }, extra);
const mc = (topic, prompt, answer, distractors, explain) => ({ type: 'mc', topic, prompt, answer, distractors, explain });

const topics = {
  sub: { unit: 1, sec: 'sub', label: 'Substitution' },
  parts: { unit: 1, sec: 'parts', label: 'Integration by parts' },
  pfd: { unit: 1, sec: 'pfd', label: 'Partial fractions' },
  trigsub: { unit: 1, sec: 'trigsub', label: 'Trig substitution' },
  area: { unit: 1, sec: 'area', label: 'Area between curves' },
  arclength: { unit: 1, sec: 'arclength', label: 'Arc length' },
  washers: { unit: 2, sec: 'washers', label: 'Disks & washers' },
  shells: { unit: 2, sec: 'shells', label: 'Shells' },
  density: { unit: 2, sec: 'density', label: 'Mass & center of mass' },
  work: { unit: 2, sec: 'work', label: 'Work' },
  fluid: { unit: 2, sec: 'fluid', label: 'Fluid force' },
  improper: { unit: 2, sec: 'improper', label: 'Improper integrals' },
  odes: { unit: 3, sec: 'odes', label: 'Differential equations' },
  qualitative: { unit: 3, sec: 'qualitative', label: 'Slope fields & equilibria' },
  euler: { unit: 3, sec: 'euler', label: 'Euler’s method' },
  separable: { unit: 3, sec: 'separable', label: 'Separable equations' },
  sequences: { unit: 4, sec: 'sequences', label: 'Sequences' },
  geometric: { unit: 4, sec: 'geometric', label: 'Geometric series' },
  series: { unit: 4, sec: 'series', label: 'Convergence tests' },
  ast: { unit: 5, sec: 'ast', label: 'Alternating series' },
  taylor: { unit: 5, sec: 'taylor', label: 'Taylor series' },
  power: { unit: 5, sec: 'power', label: 'Power series' },
  eulerformula: { unit: 5, sec: 'eulerformula', label: 'Euler’s formula' },
  fourier: { unit: 5, sec: 'fourier', label: 'Fourier series' }
};

const ladders = {
  sub: ['Find an inner function whose derivative also appears (up to a constant).', 'Write u and du, then rewrite every x and dx in terms of u.', 'For a definite integral, change the limits to u-values.'],
  parts: ['Pick u by LIATE: logs, inverse trig, algebraic, trig, exponential.', 'Write du and v, then use uv − ∫v du.', 'Check by differentiating your answer.'],
  pfd: ['Factor the denominator (long division first if the top’s degree is not smaller).', 'Write one fraction per factor: repeated factors get each power; quadratics get Ax + B.', 'Plug in the roots to find the constants, then integrate to logs.'],
  trigsub: ['Match the root: a² − x² → sin, a² + x² → tan, x² − a² → sec.', 'Replace dx too, and simplify the root to one trig function.', 'Use a right triangle to get back to x.'],
  area: ['Sketch the curves and find where they meet.', 'Integrate top minus bottom (or right minus left in y).', 'Split the interval where the curves cross.'],
  arclength: ['Find f′(x) and square it.', 'L = ∫ √(1 + (f′)²) dx over the interval.', 'Look for a perfect square under the root.'],
  washers: ['Slice perpendicular to the axis: each slice is a disk or washer.', 'Measure R and r as distances to the axis.', 'V = ∫ π(R² − r²): square first, then subtract.'],
  shells: ['Slice parallel to the axis.', 'Radius = distance to the axis; height = top − bottom.', 'V = ∫ 2π · radius · height.'],
  density: ['Mass = ∫ density.', 'Moment = ∫ x · density.', 'Center of mass = moment ÷ mass; it leans toward the heavy end.'],
  work: ['Work = force × distance, added up over slices.', 'Spring: find k from F = kx with x measured from natural length.', 'Pumping: weight of a slice × the distance it is lifted.'],
  fluid: ['Pressure = weight density × depth.', 'Slice horizontally: force on a strip = pressure × width × dy.', 'Measure y down from the surface so depth = y.'],
  improper: ['Replace ∞ (or the bad point) with a letter and take a limit.', 'Know the p-rules: ∫₁^∞ 1/xᵖ needs p > 1; ∫₀¹ 1/xᵖ needs p < 1.', 'For convergence only, compare with a p-integral or e^(−x).'],
  odes: ['Substitute the function and its derivatives into the equation.', 'Order = highest derivative.', 'Use the initial condition to find the constant.'],
  qualitative: ['Equilibria: set the right side to 0.', 'Check the sign of f(y) on each side.', 'Arrows toward it = stable; away = unstable.'],
  euler: ['Slope = f(t, y) at the current point.', 'New y = old y + Δt · slope; new t = old t + Δt.', 'Repeat from the new point, keeping a table.'],
  separable: ['Write dy/dt = g(t)·h(y) and separate.', 'Integrate both sides, add one constant.', 'Solve for y, then use the initial condition.'],
  sequences: ['Write the first few terms.', 'Treat n as x and use function limits (L’Hôpital, leading terms).', 'Remember growth order: ln n ≪ nᵖ ≪ bⁿ ≪ n!.'],
  geometric: ['Find the first term a and the ratio r.', 'If |r| < 1, the sum is a/(1 − r).', 'Check where the index starts: a is the first term written.'],
  series: ['Divergence test first: do the terms go to 0?', 'Recognize p-series and geometric series.', 'Factorials or powers like 3ᵏ: ratio test. Algebraic terms: limit comparison.'],
  ast: ['Are the signs alternating, with sizes decreasing to 0?', 'Test the absolute values for absolute convergence.', 'Error after n terms ≤ the next term.'],
  taylor: ['Coefficient of (x − a)ᵏ is f⁽ᵏ⁾(a)/k!.', 'Start from a known series and substitute or multiply.', 'Watch the signs and factorials.'],
  power: ['Ratio test with x in the terms.', 'Solve lim | … | < 1 for |x − a| to get R.', 'Check each endpoint separately.'],
  eulerformula: ['e^(iθ) = cos θ + i sin θ.', 'Use radians and the unit circle.', 'Powers: multiply the angle (De Moivre).'],
  fourier: ['Check symmetry: odd → sines only; even → cosines only.', 'aₙ = (1/π)∫ f cos nx, bₙ = (1/π)∫ f sin nx over [−π, π].', 'cos nπ = (−1)ⁿ and sin nπ = 0.']
};

const questions = [
  /* ---------------- substitution ---------------- */
  calc('sub', { vars: { a: [1, 2, 3], n: [1, 2, 3] }, let: { top: 'a^2 + 1' },
    prompt: R`Evaluate $\displaystyle\int_0^{ {{a}} } x\left(x^2+1\right)^{ {{n}} }dx$.`,
    answer: '(top^(n+1) - 1) / (2*(n+1))', decimals: 4,
    explain: R`Let $u = x^2+1$, $du = 2x\,dx$; $u$ runs from 1 to {{top}}. $\frac12\int_1^{ {{top}} }u^{ {{n}} }du = \frac{ {{top}}^{ {{= n+1}} }-1}{ {{= 2*(n+1)}} }\approx{{= answer | 4}}$.` }),
  calc('sub', { vars: { a: [1, 1.5, 2] },
    prompt: R`Evaluate $\displaystyle\int_0^{ {{a}} } x\,e^{x^2}\,dx$.`,
    answer: '(exp(a^2) - 1) / 2', decimals: 4,
    explain: R`With $u = x^2$, $x\,dx = \frac12du$ and $u$ runs from 0 to {{= a^2}}: $\frac12\left(e^{ {{= a^2}} }-1\right)\approx{{= answer | 4}}$.` }),
  calc('sub', { vars: { n: [2, 3, 4, 5, 6] },
    prompt: R`Evaluate $\displaystyle\int_0^{\pi/2}\sin^{ {{n}} }x\,\cos x\,dx$.`,
    answer: '1 / (n + 1)', decimals: 4,
    explain: R`Let $u = \sin x$, $du = \cos x\,dx$, $u$ from 0 to 1: $\int_0^1u^{ {{n}} }du = \frac{1}{ {{= n+1}} }$.` }),
  calc('sub', { vars: { m: [1, 2], n: [1, 2, 3] },
    prompt: R`Evaluate $\displaystyle\int_1^{ e^{ {{m}} } }\frac{(\ln x)^{ {{n}} }}{x}\,dx$.`,
    answer: 'm^(n+1) / (n+1)', decimals: 4,
    explain: R`Let $u = \ln x$, $du = \frac{dx}{x}$, $u$ from 0 to {{m}}: $\int_0^{ {{m}} }u^{ {{n}} }du = \frac{ {{m}}^{ {{= n+1}} } }{ {{= n+1}} }\approx{{= answer | 4}}$.` }),
  bank('sub', [
    [R`Which substitution simplifies $\int x^2\cos\left(x^3\right)dx$?`, R`$u = x^3$`, [R`$u = x^2$`, R`$u = \cos\left(x^3\right)$`, R`$u = 3x^2$`, R`$u = \sin x$`], R`$du = 3x^2\,dx$, and $x^2\,dx$ is already there: $\frac13\int\cos u\,du$.`],
    [R`$\int e^{5x}\,dx =$`, R`$\frac15e^{5x}+C$`, [R`$5e^{5x}+C$`, R`$e^{5x}+C$`, R`$\frac16e^{6x}+C$`], R`With $u = 5x$, $dx = \frac15du$.`],
    [R`$\int\sec^2(3x)\,dx =$`, R`$\frac13\tan(3x)+C$`, [R`$3\tan(3x)+C$`, R`$\tan(3x)+C$`, R`$\frac13\sec^3(3x)+C$`], R`With $u = 3x$, the $\frac13$ comes from $dx = \frac13du$.`],
    [R`$\int\frac{x}{x^2+4}\,dx =$`, R`$\frac12\ln\left(x^2+4\right)+C$`, [R`$\ln\left(x^2+4\right)+C$`, R`$\frac12\arctan\frac x2+C$`, R`$2\ln\left(x^2+4\right)+C$`], R`$u = x^2+4$, $du = 2x\,dx$, so $x\,dx = \frac12du$.`],
    [R`$\int\frac{\cos x}{\sin x}\,dx =$`, R`$\ln|\sin x|+C$`, [R`$-\ln|\sin x|+C$`, R`$\ln|\cos x|+C$`, R`$-\frac{1}{\sin^2x}+C$`], R`$u = \sin x$, $du = \cos x\,dx$: $\int\frac{du}{u}$.`],
    [R`After $u = x^2$, $\int_0^2x\,e^{x^2}\,dx$ becomes`, R`$\frac12\int_0^4e^u\,du$`, [R`$\frac12\int_0^2e^u\,du$`, R`$\int_0^4e^u\,du$`, R`$2\int_0^4e^u\,du$`], R`$x\,dx = \frac12du$, and the limits become $0^2 = 0$ and $2^2 = 4$.`],
    [R`Best way to start $\int x\sqrt{x-1}\,dx$:`, R`$u = x-1$, then replace the leftover $x$ with $u+1$`, [R`$u = \sqrt x$`, R`Partial fractions`, R`$u = x$, $dv = \sqrt{x-1}\,dx$ is the only option`], R`$\int(u+1)\sqrt u\,du = \int\left(u^{3/2}+u^{1/2}\right)du$.`],
    [R`$\int\sin^3x\cos x\,dx =$`, R`$\frac14\sin^4x+C$`, [R`$\frac14\cos^4x+C$`, R`$-\frac14\sin^4x+C$`, R`$\frac12\sin^2x+C$`], R`$u = \sin x$, $du = \cos x\,dx$: $\int u^3du = \frac{u^4}{4}$.`]
  ]),

  /* ---------------- integration by parts ---------------- */
  calc('parts', { vars: { k: [1, 2, 3] },
    prompt: R`Evaluate $\displaystyle\int_0^1x\,e^{ {{k}}x}\,dx$.`,
    answer: '(exp(k)*(k - 1) + 1) / k^2', decimals: 4,
    explain: R`$u = x$, $dv = e^{ {{k}}x}dx$: $\left[\frac{x e^{ {{k}}x}}{ {{k}} }-\frac{e^{ {{k}}x}}{ {{= k^2}} }\right]_0^1 = \frac{e^{ {{k}} }({{k}}-1)+1}{ {{= k^2}} }\approx{{= answer | 4}}$.` }),
  calc('parts', { vars: { a: [2, 3, 4, 5] },
    prompt: R`Evaluate $\displaystyle\int_1^{ {{a}} }\ln x\,dx$.`,
    answer: 'a*ln(a) - a + 1', decimals: 4,
    explain: R`$u = \ln x$, $dv = dx$: $\big[x\ln x-x\big]_1^{ {{a}} } = {{a}}\ln{{a}}-{{a}}+1\approx{{= answer | 4}}$.` }),
  calc('parts', { vars: { it: [
    { lab: R`\int_0^{\pi}x\sin x\,dx`, v: 3.14159265, how: R`$\big[-x\cos x+\sin x\big]_0^\pi = \pi$` },
    { lab: R`\int_0^{\pi/2}x\cos x\,dx`, v: 0.57079633, how: R`$\big[x\sin x+\cos x\big]_0^{\pi/2} = \frac\pi2-1$` },
    { lab: R`\int_0^1x\,e^{-x}\,dx`, v: 0.26424112, how: R`$\big[-xe^{-x}-e^{-x}\big]_0^1 = 1-\frac2e$` },
    { lab: R`\int_1^e x\ln x\,dx`, v: 2.09726402, how: R`$\left[\frac{x^2\ln x}{2}-\frac{x^2}{4}\right]_1^e = \frac{e^2+1}{4}$` },
    { lab: R`\int_0^1\arctan x\,dx`, v: 0.43882457, how: R`$\left[x\arctan x-\frac12\ln\left(1+x^2\right)\right]_0^1 = \frac\pi4-\frac{\ln2}{2}$` },
    { lab: R`\int_0^{\pi}e^x\sin x\,dx`, v: 12.07034632, how: R`parts twice gives $\frac{e^x(\sin x-\cos x)}{2}$, so the value is $\frac{e^\pi+1}{2}$` }
  ] },
    prompt: R`Evaluate $\displaystyle {{lab}}$.`, answer: 'v', decimals: 4,
    explain: R`Integration by parts: {{how}} $\approx{{= v | 4}}$.` }),
  bank('parts', [
    [R`For $\int x^3\ln x\,dx$, choose $u =$`, R`$\ln x$`, [R`$x^3$`, R`$x^3\ln x$`, R`$\frac1x$`], R`L comes before A in LIATE: $\ln x$ simplifies when differentiated, and $x^3$ is easy to integrate.`],
    [R`For $\int x\,e^{2x}\,dx$, choose $u =$`, R`$x$`, [R`$e^{2x}$`, R`$x\,e^{2x}$`, R`$2x$`], R`Differentiating $x$ gives 1, which kills the power.`],
    [R`$\int x\sin x\,dx =$`, R`$-x\cos x+\sin x+C$`, [R`$x\cos x-\sin x+C$`, R`$-x\cos x-\sin x+C$`, R`$x\sin x+\cos x+C$`], R`$u = x$, $v = -\cos x$: $-x\cos x+\int\cos x\,dx$.`],
    [R`$\int\ln x\,dx =$`, R`$x\ln x-x+C$`, [R`$\frac1x+C$`, R`$x\ln x+C$`, R`$\frac{(\ln x)^2}{2}+C$`], R`$u = \ln x$, $dv = dx$: $x\ln x-\int x\cdot\frac1x\,dx$.`],
    [R`With $u$ = the power of $x$, how many rounds of parts does $\int x^3e^x\,dx$ take?`, '3', ['1', '2', '4'], R`Each round lowers the power by one: $x^3\to x^2\to x\to1$.`],
    [R`In $\int e^x\cos x\,dx$, after two rounds of parts`, R`the original integral reappears, so solve for it algebraically`, [R`the integral becomes 0`, R`you must switch to substitution`, R`the integral diverges`], R`$I = e^x\sin x+e^x\cos x-I$, so $I = \frac{e^x(\sin x+\cos x)}{2}+C$.`],
    [R`For $\int\arctan x\,dx$, the right choice is`, R`$u = \arctan x$, $dv = dx$`, [R`$u = 1$, $dv = \arctan x\,dx$`, R`$u = x$, $dv = \arctan x\,dx$`, R`$u = \frac{1}{1+x^2}$, $dv = dx$`], R`Then $\int\arctan x\,dx = x\arctan x-\frac12\ln\left(1+x^2\right)+C$.`],
    [R`$\int x^2\cos x\,dx =$`, R`$x^2\sin x+2x\cos x-2\sin x+C$`, [R`$x^2\sin x-2x\cos x-2\sin x+C$`, R`$x^2\sin x+2x\cos x+2\sin x+C$`, R`$-x^2\sin x+2x\cos x+C$`], R`A table: $x^2, 2x, 2, 0$ against $\sin x, -\cos x, -\sin x$ with signs $+,-,+$.`]
  ]),

  /* ---------------- partial fractions ---------------- */
  calc('pfd', { vars: { p: [1, 2, 3], q: [-1, -2, -3] }, let: { qq: '-q', c: 'p + 1', d: 'p + 3', g: 'p - q' },
    prompt: R`Evaluate $\displaystyle\int_{ {{c}} }^{ {{d}} }\frac{dx}{(x-{{p}})(x+{{qq}})}$.`,
    answer: '(ln((d - p)/(c - p)) - ln((d - q)/(c - q))) / g', decimals: 4,
    explain: R`$\frac{1}{(x-{{p}})(x+{{qq}})} = \frac{1}{ {{g}} }\left(\frac{1}{x-{{p}}}-\frac{1}{x+{{qq}}}\right)$, so the integral is $\frac{1}{ {{g}} }\Big[\ln|x-{{p}}|-\ln|x+{{qq}}|\Big]_{ {{c}} }^{ {{d}} }\approx{{= answer | 4}}$.` }),
  cmc('pfd', { vars: { p: [1, 2, 3, 4], q: [-1, -2, -3] }, let: { qq: '-q', g: 'p - q' },
    prompt: R`In $\frac{1}{(x-{{p}})(x+{{qq}})} = \frac{A}{x-{{p}}}+\frac{B}{x+{{qq}}}$, what is $A$?`,
    answer: '"1/" + str(g)', distractors: ['"-1/" + str(g)', 'str(g)', '"1/" + str(p)', '"1/" + str(qq)'],
    explain: R`Clear denominators: $1 = A(x+{{qq}})+B(x-{{p}})$. At $x = {{p}}$: $1 = {{g}}A$, so $A = \frac{1}{ {{g}} }$.` }),
  bank('pfd', [
    [R`The partial fraction form of $\frac{3x+1}{(x-2)(x+5)}$ is`, R`$\frac{A}{x-2}+\frac{B}{x+5}$`, [R`$\frac{A}{x-2}+\frac{B}{(x+5)^2}$`, R`$\frac{A}{x+2}+\frac{B}{x-5}$`, R`$\frac{Ax+B}{x-2}$`], R`Two distinct linear factors: one constant over each.`],
    [R`The partial fraction form of $\frac{1}{x^2(x-1)}$ is`, R`$\frac Ax+\frac{B}{x^2}+\frac{C}{x-1}$`, [R`$\frac{A}{x^2}+\frac{B}{x-1}$`, R`$\frac Ax+\frac{B}{x-1}$`, R`$\frac{A}{x^2(x-1)}$`], R`A repeated factor $x^2$ needs both $\frac Ax$ and $\frac{B}{x^2}$.`],
    [R`The partial fraction form of $\frac{x+3}{(x+1)\left(x^2+1\right)}$ is`, R`$\frac{A}{x+1}+\frac{Bx+C}{x^2+1}$`, [R`$\frac{A}{x+1}+\frac{B}{x^2+1}$`, R`$\frac{A}{x+1}+\frac{B}{(x+1)^2}$`, R`$\frac{Ax+B}{x+1}+\frac{C}{x^2+1}$`], R`An irreducible quadratic gets a linear numerator $Bx+C$.`],
    [R`First step for $\int\frac{x^3+1}{x^2-1}\,dx$:`, R`Polynomial long division`, [R`Partial fractions right away`, R`Trig substitution $x = \sec\theta$`, R`Substitution $u = x^2-1$`], R`The top's degree (3) is not smaller than the bottom's (2), so divide first.`],
    [R`$\int\frac{dx}{x^2+9} =$`, R`$\frac13\arctan\frac x3+C$`, [R`$\arctan\frac x3+C$`, R`$\frac19\arctan\frac x9+C$`, R`$\ln\left(x^2+9\right)+C$`], R`$\int\frac{dx}{x^2+a^2} = \frac1a\arctan\frac xa$ with $a = 3$.`],
    [R`$\int\frac{dx}{x(x+1)} =$`, R`$\ln|x|-\ln|x+1|+C$`, [R`$\ln|x|+\ln|x+1|+C$`, R`$\ln|x(x+1)|+C$`, R`$\frac{1}{x+1}+C$`], R`$\frac{1}{x(x+1)} = \frac1x-\frac{1}{x+1}$.`],
    [R`In $1 = A(x+1)+B(x-1)$, setting $x = 1$ gives`, R`$A = \frac12$`, [R`$B = \frac12$`, R`$A = 1$`, R`$A = -\frac12$`], R`At $x = 1$ the $B$ term vanishes: $1 = 2A$.`]
  ]),

  /* ---------------- trig substitution ---------------- */
  calc('trigsub', { vars: { a: [1, 2, 3, 4, 5, 6] }, let: { a2: 'a^2' },
    prompt: R`Evaluate $\displaystyle\int_0^{ {{a}} }\sqrt{ {{a2}}-x^2}\,dx$.`,
    answer: 'pi * a2 / 4', decimals: 4,
    explain: R`With $x = {{a}}\sin\theta$ it becomes $\int_0^{\pi/2}{{a2}}\cos^2\theta\,d\theta = \frac{ {{a2}}\pi}{4}$: a quarter of a circle of radius {{a}}.` }),
  calc('trigsub', { vars: { a: [1, 2, 3, 4, 5] }, let: { a2: 'a^2' },
    prompt: R`Evaluate $\displaystyle\int_0^{ {{a}} }\frac{dx}{x^2+{{a2}}}$.`,
    answer: 'pi / (4*a)', decimals: 4,
    explain: R`$\int\frac{dx}{x^2+{{a2}}} = \frac{1}{ {{a}} }\arctan\frac{x}{ {{a}} }$, so the value is $\frac{1}{ {{a}} }\arctan1 = \frac{\pi}{ {{= 4*a}} }$.` }),
  calc('trigsub', { vars: { a: [2, 4, 6, 8, 10] }, let: { h: 'a / 2', a2: 'a^2' },
    prompt: R`Evaluate $\displaystyle\int_0^{ {{h}} }\frac{dx}{\sqrt{ {{a2}}-x^2}}$.`,
    answer: 'pi / 6', decimals: 4,
    explain: R`$\int\frac{dx}{\sqrt{ {{a2}}-x^2}} = \arcsin\frac{x}{ {{a}} }$, so the value is $\arcsin\frac12 = \frac\pi6$.` }),
  bank('trigsub', [
    [R`Which substitution suits $\int\sqrt{9-x^2}\,dx$?`, R`$x = 3\sin\theta$`, [R`$x = 3\tan\theta$`, R`$x = 3\sec\theta$`, R`$u = 9-x^2$`], R`$9-9\sin^2\theta = 9\cos^2\theta$.`],
    [R`Which substitution suits $\int\frac{dx}{\sqrt{x^2+16}}$?`, R`$x = 4\tan\theta$`, [R`$x = 4\sin\theta$`, R`$x = 4\sec\theta$`, R`$x = 16\tan\theta$`], R`$16\tan^2\theta+16 = 16\sec^2\theta$.`],
    [R`Which substitution suits $\int\frac{\sqrt{x^2-25}}{x}\,dx$?`, R`$x = 5\sec\theta$`, [R`$x = 5\sin\theta$`, R`$x = 5\tan\theta$`, R`$x = 25\sec\theta$`], R`$25\sec^2\theta-25 = 25\tan^2\theta$.`],
    [R`If $x = 3\sin\theta$, then $\cos\theta =$`, R`$\frac{\sqrt{9-x^2}}{3}$`, [R`$\frac{x}{3}$`, R`$\frac{3}{\sqrt{9-x^2}}$`, R`$\frac{\sqrt{9-x^2}}{x}$`], R`Triangle: opposite $x$, hypotenuse 3, adjacent $\sqrt{9-x^2}$.`],
    [R`If $x = 2\tan\theta$, then $\sqrt{4+x^2} =$`, R`$2\sec\theta$`, [R`$2\cos\theta$`, R`$2\tan\theta$`, R`$4\sec^2\theta$`], R`$4+4\tan^2\theta = 4\sec^2\theta$.`],
    [R`Best first try for $\int\frac{x}{\sqrt{1-x^2}}\,dx$:`, R`$u = 1-x^2$`, [R`$x = \sin\theta$`, R`Partial fractions`, R`Integration by parts`], R`$du = -2x\,dx$ is already there; the answer is $-\sqrt{1-x^2}+C$.`],
    [R`$\int\cos^2\theta\,d\theta =$`, R`$\frac\theta2+\frac{\sin2\theta}{4}+C$`, [R`$\frac{\cos^3\theta}{3}+C$`, R`$\frac\theta2-\frac{\sin2\theta}{4}+C$`, R`$\sin^2\theta+C$`], R`Use $\cos^2\theta = \frac{1+\cos2\theta}{2}$.`]
  ]),

  /* ---------------- area between curves ---------------- */
  calc('area', { vars: { k: [1, 2, 3, 4, 5, 6] },
    prompt: R`Find the area of the region between $y = {{k}}x$ and $y = x^2$.`,
    answer: 'k^3 / 6', decimals: 4,
    explain: R`They meet at $x = 0$ and $x = {{k}}$, with the line on top: $\int_0^{ {{k}} }\left({{k}}x-x^2\right)dx = \frac{ {{k}}^3}{2}-\frac{ {{k}}^3}{3} = \frac{ {{= k^3}} }{6}$.` }),
  calc('area', { vars: { c: [1, 2, 3] }, let: { c2: 'c^2' },
    prompt: R`Find the area of the region between $y = x^2$ and $y = {{c2}}$.`,
    answer: '4 * c^3 / 3', decimals: 4,
    explain: R`They meet at $x = \pm{{c}}$: $\int_{-{{c}}}^{ {{c}} }\left({{c2}}-x^2\right)dx = \frac{4\cdot{{c}}^3}{3} = \frac{ {{= 4*c^3}} }{3}$.` }),
  calc('area', { vars: { k: [2, 3, 4] }, let: { k2: 'k^2' },
    prompt: R`Find the area of the region between $y = \sqrt x$ and $y = \frac{x}{ {{k}} }$.`,
    answer: 'k^3 / 6', decimals: 4,
    explain: R`$\sqrt x = \frac{x}{ {{k}} }$ at $x = 0$ and $x = {{k2}}$, with $\sqrt x$ on top: $\int_0^{ {{k2}} }\left(\sqrt x-\frac{x}{ {{k}} }\right)dx = \frac23{{k}}^3-\frac{ {{k}}^3}{2} = \frac{ {{= k^3}} }{6}$.` }),
  mc('area', R`Find the area between $y = \sin x$ and $y = \cos x$ for $0\le x\le\frac\pi4$.`, R`$\sqrt2-1$`, [R`$\sqrt2+1$`, R`$1-\frac{\sqrt2}{2}$`, R`$\frac{\sqrt2}{2}$`, R`$2-\sqrt2$`], R`Cosine is on top: $\int_0^{\pi/4}(\cos x-\sin x)\,dx = \big[\sin x+\cos x\big]_0^{\pi/4} = \sqrt2-1$.`),
  bank('area', [
    [R`The area between $y = f(x)$ on top and $y = g(x)$ below on $[a,b]$ is`, R`$\int_a^b\big(f(x)-g(x)\big)\,dx$`, [R`$\int_a^b\big(g(x)-f(x)\big)\,dx$`, R`$\int_a^bf(x)g(x)\,dx$`, R`$\left|\int_a^bf\,dx\right|-\left|\int_a^bg\,dx\right|$`], R`Top minus bottom, integrated.`],
    [R`For the region between $x = y^2$ and $x = y+2$, the easiest setup is`, R`$\int_{-1}^{2}\left(y+2-y^2\right)dy$`, [R`$\int_{-1}^{2}\left(y^2-y-2\right)dy$`, R`$\int_0^4\left(\sqrt x-(x-2)\right)dx$`, R`$\int_{-1}^{2}\left(y+2+y^2\right)dy$`], R`They meet where $y^2 = y+2$: $y = -1, 2$. Right minus left in $y$ gives one integral.`],
    [R`If two curves cross at $x = c$ inside $[a,b]$, you should`, R`split at $c$ so each piece is top minus bottom`, [R`ignore it: the integral handles signs`, R`integrate $f\cdot g$`, R`use only $[a,c]$`], R`Otherwise the pieces cancel instead of adding.`],
    [R`The limits of an area-between-curves integral usually come from`, R`solving $f(x) = g(x)$`, [R`setting $f(x) = 0$`, R`setting $f'(x) = 0$`, R`the $y$-intercepts`], R`The region is bounded where the curves meet.`]
  ]),

  /* ---------------- arc length ---------------- */
  calc('arclength', { vars: { b: [3, 8, 15, 24] }, let: { s: 'sqrt(1 + b)' },
    prompt: R`Find the length of $y = \frac23x^{3/2}$ from $x = 0$ to $x = {{b}}$.`,
    answer: '2/3 * ((1 + b)^1.5 - 1)', decimals: 4,
    explain: R`$y' = \sqrt x$, so $L = \int_0^{ {{b}} }\sqrt{1+x}\,dx = \frac23\left(({{= 1+b}})^{3/2}-1\right) = \frac23\left({{= (1+b)^1.5}}-1\right)\approx{{= answer | 4}}$.` }),
  calc('arclength', { vars: { it: [{ m: 0.75, md: R`\frac34` }, { m: 1.3333333333, md: R`\frac43` }, { m: 0.4166666667, md: R`\frac{5}{12}` }, { m: 2.4, md: R`\frac{12}{5}` }], a: [4, 6, 12] },
    prompt: R`Find the length of the line $y = {{md}}x+1$ from $x = 0$ to $x = {{a}}$.`,
    answer: 'a * sqrt(1 + m^2)', decimals: 4,
    explain: R`$y' = {{md}}$ is constant: $L = \int_0^{ {{a}} }\sqrt{1+\left({{md}}\right)^2}\,dx = {{a}}\sqrt{1+\left({{md}}\right)^2}\approx{{= answer | 4}}$. (Pythagoras gives the same.)` }),
  calc('arclength', { vars: { b: [2, 3, 4] },
    prompt: R`Find the length of $y = \frac{x^2}{2}-\frac{\ln x}{4}$ from $x = 1$ to $x = {{b}}$.`,
    answer: '(b^2 - 1)/2 + ln(b)/4', decimals: 4,
    explain: R`$y' = x-\frac{1}{4x}$, so $1+(y')^2 = \left(x+\frac{1}{4x}\right)^2$. $L = \int_1^{ {{b}} }\left(x+\frac{1}{4x}\right)dx = \frac{ {{b}}^2-1}{2}+\frac{\ln {{b}}}{4}\approx{{= answer | 4}}$.` }),
  bank('arclength', [
    [R`The arc length of $y = x^2$ from $x = 0$ to $x = 1$ is`, R`$\int_0^1\sqrt{1+4x^2}\,dx$`, [R`$\int_0^1\sqrt{1+x^4}\,dx$`, R`$\int_0^1\left(1+2x\right)dx$`, R`$\int_0^1\sqrt{1+2x}\,dx$`], R`$f' = 2x$, so $(f')^2 = 4x^2$.`],
    [R`The arc length of $y = \sin x$ on $[0,\pi]$ is`, R`$\int_0^\pi\sqrt{1+\cos^2x}\,dx$`, [R`$\int_0^\pi\sqrt{1+\sin^2x}\,dx$`, R`$\int_0^\pi(1+\cos x)\,dx$`, R`$\int_0^\pi\sqrt{\cos x}\,dx$`], R`$f' = \cos x$.`],
    [R`For the curve $x = y^3$, $0\le y\le1$, the length is`, R`$\int_0^1\sqrt{1+9y^4}\,dy$`, [R`$\int_0^1\sqrt{1+3y^2}\,dy$`, R`$\int_0^1\sqrt{1+y^6}\,dy$`, R`$\int_0^1\left(1+9y^4\right)dy$`], R`Use $\frac{dx}{dy} = 3y^2$, squared: $9y^4$.`],
    [R`The arc length formula comes from`, R`the Pythagorean theorem on small pieces`, [R`the area of rectangles`, R`the chain rule`, R`the volume of disks`], R`$\Delta L\approx\sqrt{\Delta x^2+\Delta y^2}$.`]
  ]),

  /* ---------------- washers ---------------- */
  calc('washers', { vars: { b: [1, 2, 3, 4, 5, 6] },
    prompt: R`The region under $y = \sqrt x$ for $0\le x\le{{b}}$ is revolved about the $x$-axis. Find the volume.`,
    answer: 'pi * b^2 / 2', decimals: 4,
    explain: R`Disks of radius $\sqrt x$: $V = \pi\int_0^{ {{b}} }x\,dx = \frac{\pi\cdot{{= b^2}}}{2}\approx{{= answer | 4}}$.` }),
  calc('washers', { vars: { k: [1, 2] },
    prompt: R`The region between $y = {{k}}x$ and $y = x^2$ is revolved about the $x$-axis. Find the volume.`,
    answer: '2 * pi * k^5 / 15', decimals: 4,
    explain: R`On $[0,{{k}}]$: $R = {{k}}x$, $r = x^2$. $V = \pi\int_0^{ {{k}} }\left({{= k^2}}x^2-x^4\right)dx = \pi\left(\frac{ {{= k^5}} }{3}-\frac{ {{= k^5}} }{5}\right) = \frac{ {{= 2*k^5}}\pi}{15}$.` }),
  calc('washers', { vars: { r: [1, 2, 3, 4], h: [3, 6, 9] },
    prompt: R`The region under $y = \frac{ {{r}} }{ {{h}} }x$ for $0\le x\le{{h}}$ is revolved about the $x$-axis, making a cone. Find its volume.`,
    answer: 'pi * r^2 * h / 3', decimals: 4,
    explain: R`$V = \pi\int_0^{ {{h}} }\left(\frac{ {{r}} }{ {{h}} }x\right)^2dx = \frac{\pi\cdot{{r}}^2\cdot{{h}}}{3}\approx{{= answer | 4}}$, the cone formula.` }),
  calc('washers', { vars: { c: [1, 2, 3] },
    prompt: R`The region under $y = x^2$ for $0\le x\le1$ is revolved about the line $y = -{{c}}$. Find the volume.`,
    answer: 'pi * (1/5 + 2*c/3)', decimals: 4,
    explain: R`Outer radius $x^2+{{c}}$, inner radius {{c}}: $V = \pi\int_0^1\left[\left(x^2+{{c}}\right)^2-{{c}}^2\right]dx = \pi\int_0^1\left(x^4+{{= 2*c}}x^2\right)dx = \pi\left(\frac15+\frac{ {{= 2*c}} }{3}\right)\approx{{= answer | 4}}$.` }),
  bank('washers', [
    [R`The washer method's area of a slice is`, R`$\pi\left(R^2-r^2\right)$`, [R`$\pi(R-r)^2$`, R`$2\pi Rr$`, R`$\pi R^2-r^2$`], R`Outer disk minus inner disk.`],
    [R`Revolving $y = f(x)\ge0$ about $y = -2$, the radius of the curve is`, R`$f(x)+2$`, [R`$f(x)-2$`, R`$f(x)$`, R`$2-f(x)$`], R`Radius = distance from the curve down to the line $y = -2$.`],
    [R`Washers about the $x$-axis use slices that are`, R`perpendicular to the $x$-axis (thickness $dx$)`, [R`parallel to the $x$-axis`, R`thickness $dy$`, R`cylindrical shells`], R`Washers are perpendicular to the axis of rotation.`],
    [R`A solid has base $0\le x\le2$ under $y = x$ and square cross-sections perpendicular to the $x$-axis. Its volume is`, R`$\int_0^2x^2\,dx = \frac83$`, [R`$\int_0^2\pi x^2\,dx$`, R`$\int_0^2x\,dx$`, R`$\int_0^2 2x^2\,dx$`], R`Each square has side $x$, so area $x^2$.`]
  ]),

  /* ---------------- shells ---------------- */
  calc('shells', { vars: { b: [1, 2, 3] },
    prompt: R`The region under $y = x^2$ for $0\le x\le{{b}}$ is revolved about the $y$-axis. Find the volume.`,
    answer: 'pi * b^4 / 2', decimals: 4,
    explain: R`Shells: radius $x$, height $x^2$. $V = \int_0^{ {{b}} }2\pi x^3\,dx = \frac{\pi\cdot{{= b^4}}}{2}\approx{{= answer | 4}}$.` }),
  calc('shells', { vars: { b: [1, 4, 9] },
    prompt: R`The region under $y = \sqrt x$ for $0\le x\le{{b}}$ is revolved about the $y$-axis. Find the volume.`,
    answer: '4 * pi * b^2.5 / 5', decimals: 4,
    explain: R`$V = \int_0^{ {{b}} }2\pi x\sqrt x\,dx = 2\pi\cdot\frac25x^{5/2}\Big|_0^{ {{b}} } = \frac{4\pi}{5}\cdot{{= b^2.5}}\approx{{= answer | 4}}$.` }),
  calc('shells', { vars: { k: [1, 2, 3] },
    prompt: R`The region between $y = {{k}}x$ and $y = x^2$ is revolved about the $y$-axis. Find the volume.`,
    answer: 'pi * k^4 / 6', decimals: 4,
    explain: R`Radius $x$, height $ {{k}}x-x^2$: $V = \int_0^{ {{k}} }2\pi x\left({{k}}x-x^2\right)dx = 2\pi\left(\frac{ {{= k^4}} }{3}-\frac{ {{= k^4}} }{4}\right) = \frac{ {{= k^4}}\pi}{6}$.` }),
  calc('shells', { vars: { b: [1, 2], c: [1, 2] },
    prompt: R`The region under $y = x^2$ for $0\le x\le{{b}}$ is revolved about the line $x = -{{c}}$. Find the volume.`,
    answer: '2 * pi * (b^4/4 + c * b^3/3)', decimals: 4,
    explain: R`Radius $x+{{c}}$, height $x^2$: $V = \int_0^{ {{b}} }2\pi(x+{{c}})x^2\,dx = 2\pi\left(\frac{ {{= b^4}} }{4}+\frac{ {{= c*b^3}} }{3}\right)\approx{{= answer | 4}}$.` }),
  bank('shells', [
    [R`The shell method's volume element is`, R`$2\pi\,(\text{radius})(\text{height})\,(\text{thickness})$`, [R`$\pi(\text{radius})^2(\text{thickness})$`, R`$\pi\left(R^2-r^2\right)(\text{thickness})$`, R`$2\pi(\text{radius})^2(\text{thickness})$`], R`Unroll a shell: a thin box $2\pi r$ long, $h$ high, $dx$ thick.`],
    [R`Revolving about $x = 3$ a region with $0\le x\le2$, the shell radius is`, R`$3-x$`, [R`$x-3$`, R`$x$`, R`$x+3$`], R`Distance from $x$ to the line $x = 3$, which lies to the right.`],
    [R`Shells slice the region`, R`parallel to the axis of rotation`, [R`perpendicular to the axis of rotation`, R`always with $dy$`, R`into disks`], R`Parallel strips sweep out shells.`],
    [R`For the region under $y = e^{-x^2}$, $0\le x\le1$, about the $y$-axis, the better method is`, R`shells: $\int_0^12\pi x\,e^{-x^2}dx$`, [R`washers in $y$`, R`disks in $x$`, R`either is equally easy`], R`Shells give a $u$-substitution; washers would need $x = \sqrt{-\ln y}$.`]
  ]),

  /* ---------------- density ---------------- */
  calc('density', { vars: { a: [1, 2, 3], b: [1, 2], L: [2, 3, 4] },
    prompt: R`A rod lies on $0\le x\le{{L}}$ m with density $\rho(x) = {{a}}+{{b}}x$ kg/m. Find its mass.`,
    answer: 'a*L + b*L^2/2', decimals: 3, unit: 'kg',
    explain: R`$M = \int_0^{ {{L}} }({{a}}+{{b}}x)\,dx = {{= a*L}}+{{= b*L^2/2}} = {{= answer | 3}}$ kg.` }),
  calc('density', { vars: { a: [1, 2, 3], b: [1, 2], L: [2, 3, 4] }, let: { M: 'a*L + b*L^2/2', mom: 'a*L^2/2 + b*L^3/3' },
    prompt: R`A rod lies on $0\le x\le{{L}}$ m with density $\rho(x) = {{a}}+{{b}}x$ kg/m. Find its center of mass.`,
    answer: 'mom / M', decimals: 3, unit: 'm',
    explain: R`Mass $= {{= M | 3}}$ kg. Moment $= \int_0^{ {{L}} }x({{a}}+{{b}}x)\,dx = {{= mom | 3}}$. $\bar x = {{= answer | 3}}$ m, right of the midpoint {{= L/2}} because the rod is heavier on the right.` }),
  calc('density', { vars: { m1: [1, 2, 3, 4], m2: [1, 2, 3, 5], m3: [2, 4, 6], x1: [-3, -2, -1, 0], x2: [1, 2, 3], x3: [4, 5, 6] },
    prompt: R`Masses of {{m1}} kg, {{m2}} kg and {{m3}} kg sit at $x = {{x1}}$, $ {{x2}}$ and $ {{x3}}$ m. Find the center of mass.`,
    answer: '(m1*x1 + m2*x2 + m3*x3) / (m1 + m2 + m3)', decimals: 3, unit: 'm',
    explain: R`$\bar x = \frac{ {{m1}}({{x1}})+{{m2}}({{x2}})+{{m3}}({{x3}})}{ {{m1}}+{{m2}}+{{m3}} } = \frac{ {{= m1*x1 + m2*x2 + m3*x3}} }{ {{= m1+m2+m3}} }\approx{{= answer | 3}}$ m.` }),
  cmc('density', { vars: { n: [1, 2, 3], L: [2, 4, 6] },
    prompt: R`A rod on $0\le x\le{{L}}$ has density $\rho(x) = x^{ {{n}} }$. Where is its center of mass?`,
    answer: '(n + 1) * L / (n + 2)', distractors: ['L / 2', 'n * L / (n + 1)', '(n + 2) * L / (n + 3)', 'L / (n + 1)'], decimals: 3, format: '$\\bar x = {}$',
    explain: R`$\bar x = \frac{\int_0^{ {{L}} }x^{ {{= n+1}} }dx}{\int_0^{ {{L}} }x^{ {{n}} }dx} = \frac{ {{L}}^{ {{= n+2}} }/{{= n+2}} }{ {{L}}^{ {{= n+1}} }/{{= n+1}} } = \frac{ {{= n+1}} }{ {{= n+2}} }\cdot{{L}}\approx{{= answer | 3}}$.` }),
  calc('density', { vars: { k: [1, 2, 3], Rr: [1, 2, 3] },
    prompt: R`A disk of radius {{Rr}} m has area density $\rho(r) = {{k}}r$ kg/m², where $r$ is the distance from the center. Find its mass.`,
    answer: '2 * pi * k * Rr^3 / 3', decimals: 3, unit: 'kg',
    explain: R`Thin rings of radius $r$ have area $2\pi r\,dr$: $M = \int_0^{ {{Rr}} }{{k}}r\cdot2\pi r\,dr = \frac{2\pi\cdot{{k}}\cdot{{= Rr^3}}}{3}\approx{{= answer | 3}}$ kg.` }),
  bank('density', [
    [R`For a rod with density $\rho(x)$ on $[a,b]$, $\int_a^bx\,\rho(x)\,dx$ is`, R`the moment about $x = 0$`, [R`the mass`, R`the center of mass`, R`the average density`], R`Divide it by the mass to get $\bar x$.`],
    [R`A rod has uniform density. Its center of mass is`, R`at its midpoint`, [R`at the heavier end`, R`at $x = 0$`, R`it depends on the length only`], R`Equal mass on each side of the middle.`],
    [R`A rod on $[0,4]$ is denser near $x = 4$. Its center of mass is`, R`greater than 2`, [R`less than 2`, R`exactly 2`, R`outside the rod`], R`It leans toward the heavier end.`],
    [R`Density is measured in kg/m along a rod. Integrating it over the rod's length gives`, R`mass in kg`, [R`density in kg/m²`, R`a length in m`, R`a moment in kg/m`], R`(kg/m)·m = kg.`]
  ]),

  /* ---------------- work ---------------- */
  calc('work', { vars: { F0: [10, 20, 30, 40], d0: [0.1, 0.2, 0.5], s1: [0, 0.1], s2: [0.3, 0.4, 0.5] }, let: { k: 'F0 / d0' },
    prompt: R`A force of {{F0}} N holds a spring stretched {{d0}} m beyond its natural length. How much work stretches it from {{s1}} m to {{s2}} m beyond natural length?`,
    answer: 'k/2 * (s2^2 - s1^2)', decimals: 3, unit: 'J',
    explain: R`$k = \frac{ {{F0}} }{ {{d0}} } = {{= k | 2}}$ N/m. $W = \int_{ {{s1}} }^{ {{s2}} }{{= k | 2}}x\,dx = \frac{ {{= k | 2}} }{2}\left({{s2}}^2-{{s1}}^2\right)\approx{{= answer | 3}}$ J.` }),
  calc('work', { vars: { L: [20, 30, 40, 50], w: [0.5, 1, 2] },
    prompt: R`A {{L}} ft rope weighing {{w}} lb/ft hangs from the top of a building. How much work pulls the whole rope up to the top?`,
    answer: 'w * L^2 / 2', decimals: 1, unit: 'ft·lb',
    explain: R`The piece at depth $y$ weighs $ {{w}}\,dy$ and rises $y$ ft: $W = \int_0^{ {{L}} }{{w}}y\,dy = \frac{ {{w}}\cdot{{L}}^2}{2} = {{= answer | 1}}$ ft·lb.` }),
  calc('work', { vars: { r: [2, 3, 4], h: [4, 6, 8, 10] },
    prompt: R`A cylindrical tank of radius {{r}} ft and height {{h}} ft is full of water (62.4 lb/ft³). How much work pumps all of it out over the top?`,
    answer: '62.4 * pi * r^2 * h^2 / 2', decimals: 0, unit: 'ft·lb',
    explain: R`A slice at depth $y$ weighs $62.4\pi({{r}})^2\,dy$ and rises $y$: $W = \int_0^{ {{h}} }62.4\pi\cdot{{= r^2}}\,y\,dy = 62.4\pi\cdot{{= r^2}}\cdot\frac{ {{= h^2}} }{2}\approx{{= answer | 0}}$ ft·lb.` }),
  calc('work', { vars: { r: [2, 3], h: [4, 6, 8], s: [1, 2, 3] },
    prompt: R`A full cylindrical water tank (62.4 lb/ft³) has radius {{r}} ft and height {{h}} ft. The water is pumped out through a spout {{s}} ft above the top. How much work does it take?`,
    answer: '62.4 * pi * r^2 * (h^2/2 + s*h)', decimals: 0, unit: 'ft·lb',
    explain: R`A slice at depth $y$ below the top rises $y+{{s}}$ ft: $W = \int_0^{ {{h}} }62.4\pi\cdot{{= r^2}}\,(y+{{s}})\,dy = 62.4\pi\cdot{{= r^2}}\left(\frac{ {{= h^2}} }{2}+{{= s*h}}\right)\approx{{= answer | 0}}$ ft·lb.` }),
  calc('work', { vars: { c: [2, 3, 5, 6], b: [2, 3, 4] },
    prompt: R`A force of $F(x) = {{c}}x^2$ N moves an object from $x = 0$ to $x = {{b}}$ m. How much work does it do?`,
    answer: 'c * b^3 / 3', decimals: 3, unit: 'J',
    explain: R`$W = \int_0^{ {{b}} }{{c}}x^2\,dx = \frac{ {{c}}\cdot{{= b^3}}}{3}\approx{{= answer | 3}}$ J.` }),
  bank('work', [
    [R`In a pumping problem, each slice's work is`, R`its weight times the distance it is lifted`, [R`its volume times its depth`, R`its mass times the tank's height`, R`its weight times the tank's height`], R`Different slices travel different distances; that is why we integrate.`],
    [R`In Hooke's law $F = kx$, $x$ is measured from`, R`the spring's natural length`, [R`the spring's attachment point`, R`the starting position of the problem`, R`its fully compressed length`], R`$x$ is the stretch (or compression) beyond natural length.`],
    [R`In SI units, the weight of a slice of water of volume $dV$ m³ is`, R`$1000\cdot9.8\,dV$ N`, [R`$1000\,dV$ N`, R`$62.4\,dV$ N`, R`$9.8\,dV$ N`], R`Mass is $1000\,dV$ kg; weight is mass times $g$.`],
    [R`The units of work in the US system are`, R`foot-pounds (ft·lb)`, [R`pounds per foot`, R`pounds per square foot`, R`joules per second`], R`Force (lb) times distance (ft).`]
  ]),

  /* ---------------- fluid force ---------------- */
  calc('fluid', { vars: { w: [2, 3, 4, 5, 6], H: [2, 3, 4, 5] },
    prompt: R`A rectangular plate {{w}} ft wide and {{H}} ft tall stands vertically in water (62.4 lb/ft³) with its top edge at the surface. Find the force on one side.`,
    answer: '62.4 * w * H^2 / 2', decimals: 1, unit: 'lb',
    explain: R`$F = \int_0^{ {{H}} }62.4\,y\cdot{{w}}\,dy = 62.4\cdot{{w}}\cdot\frac{ {{= H^2}} }{2} = {{= answer | 1}}$ lb.` }),
  calc('fluid', { vars: { w: [2, 3, 4], H: [2, 3], d: [1, 2, 3] },
    prompt: R`A rectangular plate {{w}} ft wide and {{H}} ft tall stands vertically in water (62.4 lb/ft³) with its top edge {{d}} ft below the surface. Find the force on one side.`,
    answer: '62.4 * w * ((d + H)^2 - d^2) / 2', decimals: 1, unit: 'lb',
    explain: R`Depths run from {{d}} to {{= d+H}}: $F = \int_{ {{d}} }^{ {{= d+H}} }62.4\,y\cdot{{w}}\,dy = 62.4\cdot{{w}}\cdot\frac{ {{= (d+H)^2}}-{{= d^2}} }{2} = {{= answer | 1}}$ lb.` }),
  calc('fluid', { vars: { b: [2, 4, 6], H: [3, 6] },
    prompt: R`A triangular plate stands vertically in water (62.4 lb/ft³), with its {{b}} ft base along the surface and its vertex {{H}} ft below. Find the force on one side.`,
    answer: '62.4 * b * H^2 / 6', decimals: 1, unit: 'lb',
    explain: R`At depth $y$ the width is $ {{b}}\left(1-\frac{y}{ {{H}} }\right)$. $F = \int_0^{ {{H}} }62.4\,y\cdot{{b}}\left(1-\frac{y}{ {{H}} }\right)dy = \frac{62.4\cdot{{b}}\cdot{{= H^2}}}{6} = {{= answer | 1}}$ lb.` }),
  calc('fluid', { vars: { b: [2, 4, 6], H: [3, 6] },
    prompt: R`A triangular plate stands vertically in water (62.4 lb/ft³) with its vertex at the surface and its {{b}} ft base horizontal, {{H}} ft below. Find the force on one side.`,
    answer: '62.4 * b * H^2 / 3', decimals: 1, unit: 'lb',
    explain: R`At depth $y$ the width is $\frac{ {{b}}y}{ {{H}} }$. $F = \int_0^{ {{H}} }62.4\,y\cdot\frac{ {{b}}y}{ {{H}} }\,dy = \frac{62.4\cdot{{b}}\cdot{{= H^2}}}{3} = {{= answer | 1}}$ lb.` }),
  bank('fluid', [
    [R`Water pressure at a depth of 5 ft is`, R`$62.4\cdot5 = 312$ lb/ft²`, [R`$62.4$ lb/ft²`, R`$62.4\cdot5^2$ lb/ft²`, R`$\frac{62.4}{5}$ lb/ft²`], R`$P = \delta d$.`],
    [R`For fluid force on a vertical plate, slices are horizontal because`, R`the pressure is the same along a horizontal strip`, [R`the plate is thin`, R`the width is constant`, R`vertical strips have no area`], R`Depth, and so pressure, is constant across each horizontal strip.`],
    [R`With $y$ measured down from the surface, the force on a strip at depth $y$ is`, R`$62.4\,y\,w(y)\,dy$`, [R`$62.4\,w(y)\,dy$`, R`$62.4\,y^2\,dy$`, R`$y\,w(y)\,dy$`], R`Pressure $62.4y$ times area $w(y)\,dy$.`],
    [R`Deeper water pushes harder on a dam because`, R`pressure grows in proportion to depth`, [R`the dam is thinner there`, R`water is denser at the bottom`, R`gravity is stronger there`], R`$P = \delta d$ with constant $\delta$.`]
  ]),

  /* ---------------- improper integrals ---------------- */
  calc('improper', { vars: { p: [1.5, 2, 3, 4, 5] },
    prompt: R`Evaluate $\displaystyle\int_1^\infty\frac{dx}{x^{ {{p}} }}$.`,
    answer: '1 / (p - 1)', decimals: 4,
    explain: R`$\lim_{b\to\infty}\left[\frac{x^{1-{{p}}}}{1-{{p}}}\right]_1^b = \frac{1}{ {{= p-1}} }$, since $p = {{p}}\gt1$.` }),
  calc('improper', { vars: { k: [0.5, 1, 2, 3, 4, 5] },
    prompt: R`Evaluate $\displaystyle\int_0^\infty e^{-{{k}}x}\,dx$.`,
    answer: '1 / k', decimals: 4,
    explain: R`$\lim_{b\to\infty}\left[-\frac{e^{-{{k}}x}}{ {{k}} }\right]_0^b = \frac{1}{ {{k}} }$.` }),
  calc('improper', { vars: { it: [{ pd: R`\frac12`, p: 0.5 }, { pd: R`\frac13`, p: 0.3333333333 }, { pd: R`\frac14`, p: 0.25 }, { pd: R`\frac23`, p: 0.6666666667 }] },
    prompt: R`Evaluate $\displaystyle\int_0^1\frac{dx}{x^{ {{pd}} }}$.`,
    answer: '1 / (1 - p)', decimals: 4,
    explain: R`$\lim_{a\to0^+}\left[\frac{x^{1-p}}{1-p}\right]_a^1 = \frac{1}{1-p}$ with $p = {{pd}}\lt1$: $ {{= answer | 4}}$.` }),
  calc('improper', { vars: { k: [1, 2, 3] },
    prompt: R`Evaluate $\displaystyle\int_0^\infty x\,e^{-{{k}}x}\,dx$.`,
    answer: '1 / k^2', decimals: 4,
    explain: R`Parts: $\int_0^bxe^{-{{k}}x}dx = \left[-\frac{x}{ {{k}} }e^{-{{k}}x}-\frac{1}{ {{= k^2}} }e^{-{{k}}x}\right]_0^b\to\frac{1}{ {{= k^2}} }$.` }),
  calc('improper', { vars: { a: [1, 2, 3, 4, 5] }, let: { a2: 'a^2' },
    prompt: R`Evaluate $\displaystyle\int_0^\infty\frac{dx}{x^2+{{a2}}}$.`,
    answer: 'pi / (2 * a)', decimals: 4,
    explain: R`$\lim_{b\to\infty}\frac{1}{ {{a}} }\arctan\frac{b}{ {{a}} } = \frac{1}{ {{a}} }\cdot\frac\pi2 = \frac{\pi}{ {{= 2*a}} }$.` }),
  bank('improper', [
    [R`$\int_1^\infty\frac{dx}{x}$`, 'Diverges', ['Converges to 1', 'Converges to 0', R`Converges to $\ln2$`], R`$\lim\ln b = \infty$: the $p = 1$ case diverges.`],
    [R`$\int_1^\infty\frac{dx}{\sqrt x}$`, 'Diverges', ['Converges to 2', 'Converges to 1', R`Converges to $\frac12$`], R`$p = \frac12\le1$.`],
    [R`$\int_1^\infty\frac{dx}{x^3}$`, R`Converges to $\frac12$`, ['Diverges', R`Converges to $\frac13$`, 'Converges to 1'], R`$\frac{1}{p-1}$ with $p = 3$.`],
    [R`$\int_{-1}^1\frac{dx}{x^2}$`, 'Diverges', [R`Equals $-2$`, 'Equals 2', 'Equals 0'], R`It is improper at $x = 0$, and $\int_0^1\frac{dx}{x^2}$ diverges ($p = 2\ge1$).`],
    [R`$\int_1^\infty\frac{dx}{x^2+1}$ converges because`, R`$\frac{1}{x^2+1}\le\frac{1}{x^2}$ and $\int_1^\infty\frac{dx}{x^2}$ converges`, [R`$\frac{1}{x^2+1}\ge\frac1x$`, R`the integrand goes to 0`, R`it is a $p$-integral with $p = 1$`], R`Smaller than a convergent integral: comparison test.`],
    [R`$\int_1^\infty\frac{1+\sin^2x}{x}\,dx$`, R`diverges, since the integrand is at least $\frac1x$`, [R`converges, since $\sin^2x\le1$`, R`converges to 1`, R`cannot be decided`], R`Bigger than a divergent integral: comparison test.`],
    [R`$\int_{-\infty}^{\infty}x\,dx$`, 'Diverges', [R`Equals 0 by symmetry`, 'Equals 1', R`Equals $\infty-\infty = 0$`], R`Split at 0: $\int_0^\infty x\,dx$ diverges, so the whole integral does.`]
  ]),

  /* ---------------- differential equations ---------------- */
  calc('odes', { vars: { y0: [2, 5, 10, 100], k: [0.1, 0.2, -0.3, 0.05], T: [2, 5, 10] },
    prompt: R`If $\frac{dy}{dt} = {{k}}y$ and $y(0) = {{y0}}$, find $y({{T}})$.`,
    answer: 'y0 * exp(k * T)', decimals: 3,
    explain: R`$y = {{y0}}e^{ {{k}}t}$, so $y({{T}}) = {{y0}}e^{ {{= k*T}} }\approx{{= answer | 3}}$.` }),
  calc('odes', { vars: { y0: [100, 200, 50], ratio: [2, 3, 1.5], t1: [5, 10] },
    prompt: R`A quantity grows by $\frac{dy}{dt} = ky$. It starts at {{y0}} and is {{= y0*ratio}} at $t = {{t1}}$. Find $k$.`,
    answer: 'ln(ratio) / t1', decimals: 4,
    explain: R`$ {{= y0*ratio}} = {{y0}}e^{ {{t1}}k}$, so $e^{ {{t1}}k} = {{ratio}}$ and $k = \frac{\ln {{ratio}}}{ {{t1}} }\approx{{= answer | 4}}$.` }),
  bank('odes', [
    [R`The order of $y''+3y' = t^5$ is`, '2', ['1', '3', '5'], R`The highest derivative is $y''$.`],
    [R`Is $y = \sin t$ a solution of $y''+y = 0$?`, R`Yes: $y'' = -\sin t$, so $y''+y = 0$`, [R`No: $y'' = \cos t$`, R`Only if $t = 0$`, R`No: sine solves $y' = y$`], R`Substitute and simplify.`],
    [R`Is $y = t^2$ a solution of $y' = 2y$?`, R`No: $y' = 2t$ but $2y = 2t^2$`, [R`Yes`, R`Yes, when $t\gt0$`, R`Only with $y(0) = 1$`], R`The two sides differ for most $t$.`],
    [R`$y = Ce^{3t}$ solves $y' = 3y$. With $y(0) = 4$,`, R`$y = 4e^{3t}$`, [R`$y = e^{3t}+4$`, R`$y = 3e^{4t}$`, R`$y = 4e^{t}$`], R`$y(0) = C = 4$.`],
    [R`For which $k$ does $y = e^{kt}$ solve $y'' = 9y$?`, R`$k = \pm3$`, [R`$k = 9$`, R`$k = \pm9$`, R`$k = 3$ only`], R`$k^2e^{kt} = 9e^{kt}$, so $k^2 = 9$.`],
    [R`Newton's law of cooling says`, R`$\frac{dT}{dt} = -k(T-A)$: the rate is proportional to the difference from room temperature`, [R`$\frac{dT}{dt} = -kT$`, R`$\frac{dT}{dt} = kA$`, R`$\frac{dT}{dt} = -kt$`], R`$A$ is the ambient temperature.`]
  ]),

  /* ---------------- slope fields and equilibria ---------------- */
  cmc('qualitative', { vars: { a: [2, 3, 4, 5, 6, 8] },
    prompt: R`Which equilibrium of $\frac{dy}{dt} = y({{a}}-y)$ is stable?`,
    answer: 'a', distractors: ['0', '-a', 'a / 2', '2 * a'], format: '$y = {}$',
    explain: R`Equilibria at $y = 0$ and $y = {{a}}$. The right side is positive between them and negative above {{a}}, so solutions move toward {{a}}: stable. $y = 0$ is unstable.` }),
  cmc('qualitative', { vars: { a: [1, 2, 3], b: [4, 5, 6] },
    prompt: R`Which equilibrium of $\frac{dy}{dt} = (y-{{a}})(y-{{b}})$ is stable?`,
    answer: 'a', distractors: ['b', '0', 'a + b', '(a + b) / 2'], format: '$y = {}$',
    explain: R`Below {{a}} the right side is positive, between {{a}} and {{b}} negative, above {{b}} positive. Solutions approach {{a}} from both sides (stable) and leave {{b}} (unstable).` }),
  calc('qualitative', { vars: { a: [1, 2, 3], b: [1, 2, 3], t0: [0, 1, 2], y0: [-1, 1, 2, 3] },
    prompt: R`For $\frac{dy}{dt} = {{a}}t-{{b}}y$, what is the slope of the slope-field segment at $(t,y) = ({{t0}},{{y0}})$?`,
    answer: 'a*t0 - b*y0',
    explain: R`Substitute: $ {{a}}({{t0}})-{{b}}({{y0}}) = {{answer}}$.` }),
  bank('qualitative', [
    [R`In the slope field of an autonomous equation $y' = f(y)$,`, R`segments along any horizontal line all have the same slope`, [R`segments along any vertical line all have the same slope`, R`all segments are parallel`, R`no segment is horizontal`], R`The slope depends only on $y$.`],
    [R`An equilibrium solution of $y' = f(y)$ is`, R`a constant $y = c$ with $f(c) = 0$`, [R`a point where $f'(c) = 0$`, R`a solution that passes through the origin`, R`any solution that levels off`], R`Constant functions have derivative 0.`],
    [R`For $\frac{dy}{dt} = (y-1)^2$, the equilibrium $y = 1$ is`, 'semi-stable', ['stable', 'unstable', 'not an equilibrium'], R`$(y-1)^2\ge0$: solutions rise on both sides, so they approach 1 from below and leave it above.`],
    [R`A solution starts just above an unstable equilibrium. It`, R`moves away from the equilibrium`, [R`moves toward the equilibrium`, R`stays on the equilibrium`, R`oscillates around it`], R`That is what unstable means.`],
    [R`Where $f(y)\gt0$ in $y' = f(y)$, solutions are`, 'increasing', ['decreasing', 'constant', 'concave down'], R`$y' = f(y)$ is the slope.`]
  ]),

  /* ---------------- Euler's method ---------------- */
  calc('euler', { vars: { y0: [1, 2, 3], h: [0.1, 0.2, 0.25, 0.5] }, let: { y1: 'y0 + h*(0 + y0)', y2: 'y1 + h*(h + y1)' },
    prompt: R`Use two steps of Euler's method with $\Delta t = {{h}}$ on $\frac{dy}{dt} = t+y$, $y(0) = {{y0}}$, to estimate $y({{= 2*h}})$.`,
    answer: 'y2', decimals: 4,
    explain: R`Step 1: slope $0+{{y0}} = {{y0}}$, so $y({{h}})\approx{{= y1 | 4}}$. Step 2: slope $ {{h}}+{{= y1 | 4}}$, so $y({{= 2*h}})\approx{{= y2 | 4}}$.` }),
  calc('euler', { vars: { y0: [1, 2, 10], k: [0.5, 1, 2, -1], h: [0.1, 0.2, 0.25], n: [2, 3, 4] }, where: '1 + k*h > 0',
    prompt: R`Use Euler's method with $\Delta t = {{h}}$ for {{n}} steps on $\frac{dy}{dt} = {{k}}y$, $y(0) = {{y0}}$. What estimate do you get?`,
    answer: 'y0 * (1 + k*h)^n', decimals: 4,
    explain: R`Each step multiplies by $1+{{k}}({{h}}) = {{= 1 + k*h}}$, so the estimate is $ {{y0}}({{= 1 + k*h}})^{ {{n}} }\approx{{= answer | 4}}$.` }),
  calc('euler', { vars: { t0: [0, 1, 2], y0: [1, 2, 3], h: [0.1, 0.5] },
    prompt: R`One step of Euler's method with $\Delta t = {{h}}$ on $\frac{dy}{dt} = t^2-y$, starting from $y({{t0}}) = {{y0}}$: estimate $y({{= t0 + h}})$.`,
    answer: 'y0 + h*(t0^2 - y0)', decimals: 4,
    explain: R`Slope at $({{t0}},{{y0}})$: $ {{= t0^2}}-{{y0}} = {{= t0^2 - y0}}$. New $y\approx{{y0}}+{{h}}({{= t0^2 - y0}}) = {{= answer | 4}}$.` }),
  bank('euler', [
    [R`Euler's method step is`, R`$y_{k+1} = y_k+\Delta t\,f(t_k,y_k)$`, [R`$y_{k+1} = y_k+f(t_k,y_k)$`, R`$y_{k+1} = \Delta t\,f(t_k,y_k)$`, R`$y_{k+1} = y_k+\Delta t\,f(t_{k+1},y_k)$`], R`Move along the tangent line for one step.`],
    [R`If the true solution is concave up, Euler's method`, 'underestimates', ['overestimates', 'is exact', 'diverges'], R`Tangent lines lie below a concave-up curve.`],
    [R`Halving $\Delta t$ in Euler's method makes the error roughly`, 'half as big', ['a quarter as big', 'unchanged', 'twice as big'], R`Euler's method is first order.`],
    [R`Going from $t = 0$ to $t = 2$ with $\Delta t = 0.25$ takes how many steps?`, '8', ['4', '2', '25'], R`$2/0.25 = 8$.`]
  ]),

  /* ---------------- separable equations ---------------- */
  calc('separable', { vars: { k: [1, 2], y0: [1, 2, 3], b: [0.5, 1, 1.5] },
    prompt: R`Solve $\frac{dy}{dx} = {{k}}xy$ with $y(0) = {{y0}}$ and find $y({{b}})$.`,
    answer: 'y0 * exp(k * b^2 / 2)', decimals: 4,
    explain: R`$\frac{dy}{y} = {{k}}x\,dx$ gives $\ln|y| = \frac{ {{k}}x^2}{2}+C$, so $y = {{y0}}e^{ {{k}}x^2/2}$ and $y({{b}}) = {{y0}}e^{ {{= k*b^2/2}} }\approx{{= answer | 4}}$.` }),
  calc('separable', { vars: { y0: [3, 4, 5, 6], b: [3, 4, 8, 12] },
    prompt: R`Solve $\frac{dy}{dx} = \frac{x}{y}$ with $y(0) = {{y0}}$ and find $y({{b}})$.`,
    answer: 'sqrt(b^2 + y0^2)', decimals: 4,
    explain: R`$y\,dy = x\,dx$ gives $y^2 = x^2+{{= y0^2}}$. With $y\gt0$: $y({{b}}) = \sqrt{ {{= b^2 + y0^2}} }\approx{{= answer | 4}}$.` }),
  calc('separable', { vars: { A: [18, 20, 22], T0: [80, 90, 95], k: [0.05, 0.1], t: [5, 10, 20] },
    prompt: R`Coffee at {{T0}}°C cools in a {{A}}°C room by Newton's law of cooling with $k = {{k}}$ per minute. What is its temperature after {{t}} minutes?`,
    answer: 'A + (T0 - A) * exp(-k * t)', decimals: 2, unit: '°C',
    explain: R`$T = {{A}}+({{T0}}-{{A}})e^{-{{k}}t}$, so $T({{t}}) = {{A}}+{{= T0 - A}}e^{-{{= k*t}}}\approx{{= answer | 2}}$°C.` }),
  calc('separable', { vars: { H: [5, 10, 20], t: [10, 15, 30, 40] },
    prompt: R`A substance decays by $\frac{dy}{dt} = -ky$ with a half-life of {{H}} years. What percent of it remains after {{t}} years?`,
    answer: '100 * 0.5^(t / H)', decimals: 3, unit: '%',
    explain: R`$y = y_0\left(\frac12\right)^{t/{{H}}}$, so the fraction left is $\left(\frac12\right)^{ {{= t/H}} }\approx{{= answer | 3}}\%$.` }),
  bank('separable', [
    [R`Which equation is separable?`, R`$\frac{dy}{dt} = t^2y$`, [R`$\frac{dy}{dt} = t+y$`, R`$\frac{dy}{dt} = \sin(ty)$`, R`$\frac{dy}{dt} = \ln(t+y)$`], R`$t^2y$ is a function of $t$ times a function of $y$.`],
    [R`From $\ln|y| = 2t+C$, the solution is`, R`$y = Ke^{2t}$`, [R`$y = e^{2t}+C$`, R`$y = 2t+e^C$`, R`$y = Ce^{t}$`], R`$|y| = e^Ce^{2t}$; $\pm e^C$ becomes one constant $K$.`],
    [R`The solution of $\frac{dy}{dt} = y^2$ is`, R`$y = -\frac{1}{t+C}$ (plus the equilibrium $y = 0$)`, [R`$y = Ce^{t^2}$`, R`$y = \frac{y^3}{3}+C$`, R`$y = \ln|t|+C$`], R`$\int y^{-2}dy = \int dt$ gives $-\frac1y = t+C$.`],
    [R`Separating $\frac{dy}{dt} = t\,y$ requires dividing by $y$, which can lose`, R`the equilibrium solution $y = 0$`, [R`the constant $C$`, R`the variable $t$`, R`nothing`], R`Check $y = 0$ separately: it does solve the equation.`]
  ]),

  /* ---------------- sequences ---------------- */
  calc('sequences', { vars: { a: [1, 2, 3, 4, 5, 6, 7, 8, 9], c: [2, 3, 4, 5, 6, 7], b: [1, 2, 3, 4, 5], d: [1, 2, 3, 4, 5] },
    prompt: R`Find $\displaystyle\lim_{n\to\infty}\frac{ {{a}}n+{{b}} }{ {{c}}n+{{d}} }$.`,
    answer: 'a / c', decimals: 4,
    explain: R`Divide by $n$: $\frac{ {{a}}+{{b}}/n}{ {{c}}+{{d}}/n}\to\frac{ {{a}} }{ {{c}} }$.` }),
  calc('sequences', { vars: { k: [1, 2, 3, -1] },
    prompt: R`Find $\displaystyle\lim_{n\to\infty}\left(1+\frac{ {{k}} }{n}\right)^n$.`,
    answer: 'exp(k)', decimals: 4,
    explain: R`$\left(1+\frac kn\right)^n\to e^k$, here $e^{ {{k}} }\approx{{= answer | 4}}$.` }),
  calc('sequences', { vars: { k: [1, 2, 3, 4, 5] },
    prompt: R`Find $\displaystyle\lim_{n\to\infty}n\sin\left(\frac{ {{k}} }{n}\right)$.`,
    answer: 'k',
    explain: R`Write it as $\frac{\sin({{k}}/n)}{1/n}$, an indeterminate $\frac00$. L'Hôpital (in $x$) or $\sin u\approx u$ for small $u$ gives {{k}}.` }),
  calc('sequences', { vars: { s: [1, 2, 3], r: [2, 3, 0.5], c: [1, 2] }, let: { a2: 'r*s + c', a3: 'r*a2 + c', a4: 'r*a3 + c' },
    prompt: R`A sequence has $a_1 = {{s}}$ and $a_{n+1} = {{r}}\,a_n+{{c}}$. Find $a_4$.`,
    answer: 'a4', decimals: 4,
    explain: R`$a_2 = {{= a2}}$, $a_3 = {{= a3}}$, $a_4 = {{= a4}}$.` }),
  bank('sequences', [
    [R`$a_n = (-1)^n$`, 'Diverges', ['Converges to 0', 'Converges to 1', 'Converges to −1'], R`It alternates between −1 and 1 forever.`],
    [R`$a_n = \frac{n}{n+1}$`, 'Converges to 1', ['Converges to 0', 'Diverges', R`Converges to $\frac12$`], R`Leading terms: $\frac nn = 1$.`],
    [R`$a_n = \frac{\sin n}{n}$`, 'Converges to 0', ['Diverges', 'Converges to 1', 'Oscillates without a limit'], R`Squeeze between $-\frac1n$ and $\frac1n$.`],
    [R`$a_n = \frac{\ln n}{n}$`, 'Converges to 0', ['Converges to 1', 'Diverges to ∞', R`Converges to $e$`], R`L'Hôpital: $\frac{1/x}{1}\to0$.`],
    [R`$a_n = \frac{n!}{2^n}$`, 'Diverges to ∞', ['Converges to 0', 'Converges to 1', R`Converges to $\frac12$`], R`Factorials beat exponentials.`],
    [R`$a_n = \left(\frac23\right)^n$`, 'Converges to 0', [R`Converges to $\frac23$`, 'Diverges', 'Converges to 1'], R`$|r| = \frac23\lt1$.`],
    [R`$a_n = \sqrt[n]{n}$`, 'Converges to 1', ['Converges to 0', 'Diverges', R`Converges to $e$`], R`$\ln a_n = \frac{\ln n}{n}\to0$, so $a_n\to e^0 = 1$.`],
    [R`$a_n = \cos(n\pi)$`, 'Diverges', ['Converges to 1', 'Converges to −1', 'Converges to 0'], R`$\cos(n\pi) = (-1)^n$.`]
  ]),

  /* ---------------- geometric series ---------------- */
  calc('geometric', { vars: { a: [1, 2, 3, 4, 5, 6], it: [{ r: 0.5, rs: R`\frac12` }, { r: 0.3333333333, rs: R`\frac13` }, { r: 0.6666666667, rs: R`\frac23` }, { r: 0.25, rs: R`\frac14` }, { r: 0.75, rs: R`\frac34` }, { r: -0.5, rs: R`-\frac12` }, { r: -0.3333333333, rs: R`-\frac13` }] },
    prompt: R`Find $\displaystyle\sum_{k=0}^{\infty}{{a}}\left({{rs}}\right)^k$.`,
    answer: 'a / (1 - r)', decimals: 4,
    explain: R`Geometric with first term {{a}} and $r = {{rs}}$: $\frac{ {{a}} }{1-\left({{rs}}\right)}\approx{{= answer | 4}}$.` }),
  calc('geometric', { vars: { a: [1, 2, 3, 5], it: [{ r: 0.5, rs: R`\frac12` }, { r: 0.3333333333, rs: R`\frac13` }, { r: 0.25, rs: R`\frac14` }, { r: 0.2, rs: R`\frac15` }] },
    prompt: R`Find $\displaystyle\sum_{k=1}^{\infty}{{a}}\left({{rs}}\right)^k$.`,
    answer: 'a * r / (1 - r)', decimals: 4,
    explain: R`The first term (at $k = 1$) is $ {{a}}\cdot{{rs}}$, and $r = {{rs}}$: $\frac{ {{a}}\cdot{{rs}} }{1-{{rs}}}\approx{{= answer | 4}}$.` }),
  calc('geometric', { vars: { a: [1, 2, 3], r: [2, 3], n: [4, 5, 6] }, let: { m: 'n - 1' },
    prompt: R`Find $\displaystyle\sum_{k=0}^{ {{m}} }{{a}}\cdot{{r}}^k$.`,
    answer: 'a * (r^n - 1) / (r - 1)',
    explain: R`{{n}} terms of a geometric sum: $ {{a}}\cdot\frac{ {{r}}^{ {{n}} }-1}{ {{r}}-1} = {{answer}}$.` }),
  calc('geometric', { vars: { H: [4, 6, 10, 12], r: [0.5, 0.6, 0.75, 0.8] },
    prompt: R`A ball is dropped from {{H}} ft and each bounce rises to {{r}} of the previous height. What total vertical distance does it travel?`,
    answer: 'H * (1 + r) / (1 - r)', decimals: 3, unit: 'ft',
    explain: R`Down {{H}}, then up and down $2\cdot{{H}}({{r}})^k$ for $k\ge1$: $ {{H}}+\frac{2\cdot{{H}}\cdot{{r}}}{1-{{r}}}\approx{{= answer | 3}}$ ft.` }),
  calc('geometric', { vars: { D: [50, 100, 200], f: [0.2, 0.25, 0.5] },
    prompt: R`A patient takes {{D}} mg of a drug every day, and a fraction {{f}} of the amount in the body remains a day later. In the long run, how much is in the body right after a dose?`,
    answer: 'D / (1 - f)', decimals: 2, unit: 'mg',
    explain: R`After many doses: $ {{D}}+{{D}}({{f}})+{{D}}({{f}})^2+\cdots = \frac{ {{D}} }{1-{{f}}}\approx{{= answer | 2}}$ mg.` }),
  bank('geometric', [
    [R`$\sum_{k=0}^\infty\left(\frac32\right)^k$`, 'Diverges', ['Converges to −2', 'Converges to 2', R`Converges to $\frac32$`], R`$|r| = \frac32\ge1$.`],
    [R`$0.\overline{7} = 0.777\ldots$ as a fraction is`, R`$\frac79$`, [R`$\frac{7}{10}$`, R`$\frac{7}{99}$`, R`$\frac{77}{100}$`], R`$\frac{7/10}{1-1/10} = \frac79$.`],
    [R`$\sum_{k=0}^\infty\frac{3^k}{4^k}$`, 'Converges to 4', ['Converges to 3', R`Converges to $\frac34$`, 'Diverges'], R`$r = \frac34$: $\frac{1}{1-3/4} = 4$.`],
    [R`$\sum_{k=2}^\infty\left(\frac12\right)^k$`, R`Converges to $\frac12$`, ['Converges to 2', 'Converges to 1', R`Converges to $\frac14$`], R`First term $\frac14$: $\frac{1/4}{1/2} = \frac12$.`],
    [R`A geometric series converges exactly when`, R`$|r|\lt1$`, [R`$r\lt1$`, R`$|r|\le1$`, R`$a\lt1$`], R`For $r\le-1$ or $r\ge1$ the terms do not shrink to 0.`]
  ]),

  /* ---------------- convergence tests ---------------- */
  cmc('series', { vars: { m: [1, 2, 3], c: [2, 3, 4, 5] },
    prompt: R`For $\sum\frac{k^{ {{m}} }}{ {{c}}^k}$, the ratio test limit $L = \lim\left|\frac{a_{k+1}}{a_k}\right|$ is`,
    answer: '"1/" + str(c)', distractors: ['str(c)', '"1"', '"0"', 'str(m) + "/" + str(c)'],
    explain: R`$\frac{(k+1)^{ {{m}} } }{ {{c}}^{k+1} }\cdot\frac{ {{c}}^k}{k^{ {{m}} } } = \left(\frac{k+1}{k}\right)^{ {{m}} }\frac{1}{ {{c}} }\to\frac{1}{ {{c}} }\lt1$: the series converges.` }),
  cmc('series', { vars: { c: [2, 3, 5, 10] },
    prompt: R`For $\sum\frac{ {{c}}^k}{k!}$, the ratio test limit is`,
    answer: '"0"', distractors: ['str(c)', '"1"', '"1/" + str(c)', '"∞"'],
    explain: R`$\frac{ {{c}}^{k+1} }{(k+1)!}\cdot\frac{k!}{ {{c}}^k} = \frac{ {{c}} }{k+1}\to0$: the series converges.` }),
  calc('series', { vars: { N: [9, 19, 49, 99] },
    prompt: R`Find the partial sum $\displaystyle\sum_{k=1}^{ {{N}} }\frac{1}{k(k+1)}$.`,
    answer: 'N / (N + 1)', decimals: 4,
    explain: R`$\frac{1}{k(k+1)} = \frac1k-\frac{1}{k+1}$ telescopes: $1-\frac{1}{ {{= N+1}} } = \frac{ {{N}} }{ {{= N+1}} }$. (The infinite sum is 1.)` }),
  calc('series', { vars: { it: [{ m: 1, v: 1, how: R`$1$` }, { m: 2, v: 0.75, how: R`$\frac12\left(1+\frac12\right)$` }, { m: 3, v: 0.6111111111, how: R`$\frac13\left(1+\frac12+\frac13\right)$` }] },
    prompt: R`Find $\displaystyle\sum_{k=1}^{\infty}\frac{1}{k(k+{{m}})}$.`,
    answer: 'v', decimals: 4,
    explain: R`$\frac{1}{k(k+{{m}})} = \frac{1}{ {{m}} }\left(\frac1k-\frac{1}{k+{{m}}}\right)$ telescopes, leaving the first {{m}} terms of $\frac1k$, divided by {{m}}: {{how}} $\approx{{= v | 4}}$.` }),
  bank('series', [
    [R`$\sum\frac{k}{2k+1}$`, R`Diverges by the divergence test`, [R`Converges by the ratio test`, R`Converges: it is a $p$-series`, R`Converges because the terms are less than 1`], R`The terms go to $\frac12\ne0$.`],
    [R`$\sum\frac1k$ (the harmonic series)`, 'Diverges', ['Converges to 1', R`Converges to $\ln2$`, 'Converges because the terms go to 0'], R`It is the $p = 1$ series; compare with $\int_1^\infty\frac{dx}{x}$.`],
    [R`$\sum\frac{1}{k^{1.01}}$`, R`Converges ($p$-series with $p\gt1$)`, [R`Diverges ($p$ is too close to 1)`, R`Diverges by the divergence test`, R`The ratio test proves it converges`], R`Any $p\gt1$ converges.`],
    [R`If $\lim a_k = 0$, then $\sum a_k$`, R`may converge or diverge`, ['converges', 'diverges', 'converges to 0'], R`The divergence test gives no information here.`],
    [R`The ratio test gives $L = 1$. You conclude`, R`nothing; try another test`, ['the series converges', 'the series diverges', 'the sum is 1'], R`$\sum\frac1k$ and $\sum\frac{1}{k^2}$ both give $L = 1$.`],
    [R`Best test for $\sum\frac{k^2}{3^k}$:`, 'Ratio test', [R`$p$-series`, 'Integral test with no substitution', 'Alternating series test'], R`An exponential in the denominator suits the ratio test.`],
    [R`$\sum\frac{k+1}{k^3+2}$ is best compared with`, R`$\sum\frac{1}{k^2}$ (limit comparison): it converges`, [R`$\sum\frac1k$: it diverges`, R`$\sum\frac{1}{k^3}$: it diverges`, R`$\sum 1$: it diverges`], R`Leading terms: $\frac{k}{k^3} = \frac{1}{k^2}$.`],
    [R`The integral test needs $f$ to be`, R`positive, continuous and decreasing`, [R`increasing and bounded`, R`alternating`, R`a polynomial`], R`Then the sum and $\int_1^\infty f$ behave the same.`]
  ]),

  /* ---------------- alternating series ---------------- */
  calc('ast', { vars: { p: [1, 2], it: [{ eps: 0.01, es: '0.01' }, { eps: 0.001, es: '0.001' }, { eps: 0.0001, es: '0.0001' }] },
    prompt: R`How many terms of $\displaystyle\sum_{k=1}^\infty\frac{(-1)^{k+1}}{k^{ {{p}} }}$ guarantee, by the alternating series error bound, an error less than {{es}}?`,
    answer: 'floor((1/eps)^(1/p) + 0.000001)',
    explain: R`We need $b_{n+1} = \frac{1}{(n+1)^{ {{p}} }}\lt{{es}}$, so $n+1\gt\left(\frac{1}{ {{es}} }\right)^{1/{{p}}}$. The smallest such $n$ is {{answer}}.` }),
  calc('ast', { vars: { n: [4, 9, 19, 99] },
    prompt: R`You add the first {{n}} terms of $\displaystyle\sum_{k=1}^\infty\frac{(-1)^{k+1}}{k}$. What bound does the alternating series test give on the error?`,
    answer: '1 / (n + 1)', decimals: 4,
    explain: R`The error is at most the next term: $\frac{1}{ {{= n+1}} }\approx{{= answer | 4}}$.` }),
  calc('ast', { vars: { n: [3, 4, 5] }, let: { s3: '1 - 1/2 + 1/6', s4: 's3 - 1/24', s5: 's4 + 1/120' },
    prompt: R`Find the partial sum $S_{ {{n}} }$ of $\displaystyle\sum_{k=1}^\infty\frac{(-1)^{k+1}}{k!}$.`,
    answer: 'n == 3 ? s3 : (n == 4 ? s4 : s5)', decimals: 4,
    explain: R`$1-\frac12+\frac16-\frac1{24}+\frac1{120}-\cdots$; the first {{n}} terms add to $ {{= answer | 4}}$. (The full sum is $1-\frac1e\approx0.6321$.)` }),
  bank('ast', [
    [R`$\sum\frac{(-1)^k}{\sqrt k}$`, 'Converges conditionally', ['Converges absolutely', 'Diverges', 'Converges to 0'], R`The alternating series test applies, but $\sum\frac{1}{\sqrt k}$ diverges.`],
    [R`$\sum\frac{(-1)^k}{k^2}$`, 'Converges absolutely', ['Converges conditionally', 'Diverges', 'Cannot be decided'], R`$\sum\frac{1}{k^2}$ converges.`],
    [R`$\sum(-1)^k\frac{k}{k+1}$`, 'Diverges', ['Converges conditionally', 'Converges absolutely', R`Converges to $\frac12$`], R`The terms do not go to 0.`],
    [R`The alternating series test can show that a series`, 'converges', ['diverges', 'converges absolutely', 'has a particular sum'], R`It only proves convergence.`],
    [R`$\sum_{k=1}^\infty\frac{(-1)^{k+1}}{k} =$`, R`$\ln2$`, ['1', R`$\frac{\pi^2}{6}$`, 'It diverges'], R`It is the series for $\ln(1+x)$ at $x = 1$.`],
    [R`If $\sum|a_k|$ converges, then $\sum a_k$`, 'converges', ['may diverge', 'diverges', 'converges conditionally'], R`Absolute convergence implies convergence.`]
  ]),

  /* ---------------- Taylor series ---------------- */
  calc('taylor', { vars: { a: [2, 3, -1], k: [2, 3, 4] },
    prompt: R`What is the coefficient of $x^{ {{k}} }$ in the Maclaurin series of $e^{ {{a}}x}$?`,
    answer: 'a^k / fact(k)', decimals: 4,
    explain: R`$e^{ {{a}}x} = \sum\frac{({{a}}x)^n}{n!}$, so the coefficient is $\frac{({{a}})^{ {{k}} } }{ {{k}}!} = \frac{ {{= a^k}} }{ {{= fact(k)}} }\approx{{= answer | 4}}$.` }),
  calc('taylor', { vars: { n: [2, 3], x: [0.1, 0.2, 0.5] }, let: { p2: '1 + x + x^2/2', p3: 'p2 + x^3/6' },
    prompt: R`Use the degree-{{n}} Maclaurin polynomial of $e^x$ to estimate $e^{ {{x}} }$.`,
    answer: 'n == 2 ? p2 : p3', decimals: 6,
    explain: R`$P_2(x) = 1+x+\frac{x^2}{2}$ and $P_3(x) = P_2(x)+\frac{x^3}{6}$. At $x = {{x}}$: $P_{ {{n}} }({{x}})\approx{{= answer | 6}}$, close to $e^{ {{x}} }\approx{{= exp(x) | 6}}$.` }),
  calc('taylor', { vars: { x: [0.1, 0.2, 0.3, 0.5] },
    prompt: R`Use $P_3(x) = x-\frac{x^3}{6}$ to estimate $\sin({{x}})$.`,
    answer: 'x - x^3/6', decimals: 6,
    explain: R`$ {{x}}-\frac{ {{x}}^3}{6}\approx{{= answer | 6}}$. The error is at most the next term, $\frac{ {{x}}^5}{120}$.` }),
  calc('taylor', { vars: { b: [2, 3], k: [2, 3, 4] },
    prompt: R`If $f(x) = \displaystyle\sum_{n=0}^\infty\frac{(n+1)\,x^n}{ {{b}}^n}$, find $f^{({{k}})}(0)$.`,
    answer: 'fact(k) * (k + 1) / b^k', decimals: 4,
    explain: R`The coefficient of $x^{ {{k}} }$ is $c_{ {{k}} } = \frac{ {{= k+1}} }{ {{= b^k}} }$, and $f^{({{k}})}(0) = {{k}}!\,c_{ {{k}} } = {{= fact(k)}}\cdot\frac{ {{= k+1}} }{ {{= b^k}} }\approx{{= answer | 4}}$.` }),
  calc('taylor', { vars: { a: [2, 3], h: [0.1, 0.2, -0.1] }, let: { a2: 'a^2', xv: 'a^2 + h' },
    prompt: R`Use the degree-2 Taylor polynomial of $\sqrt x$ at $x = {{a2}}$ to estimate $\sqrt{ {{xv}} }$.`,
    answer: 'a + h/(2*a) - h^2/(8*a^3)', decimals: 6,
    explain: R`$f({{a2}}) = {{a}}$, $f' = \frac{1}{2\sqrt x}\to\frac{1}{ {{= 2*a}} }$, $f'' = -\frac{1}{4x^{3/2}}\to-\frac{1}{ {{= 4*a^3}} }$. $P_2 = {{a}}+\frac{ {{h}} }{ {{= 2*a}} }-\frac{({{h}})^2}{ {{= 8*a^3}} }\approx{{= answer | 6}}$.` }),
  bank('taylor', [
    [R`$\sum_{k=0}^\infty\frac{x^k}{k!}$ is the Maclaurin series of`, R`$e^x$`, [R`$\frac{1}{1-x}$`, R`$\sin x$`, R`$\ln(1+x)$`], R`Every derivative of $e^x$ at 0 is 1.`],
    [R`$x-\frac{x^3}{3!}+\frac{x^5}{5!}-\cdots$ is`, R`$\sin x$`, [R`$\cos x$`, R`$e^{-x}$`, R`$\arctan x$`], R`Odd powers, factorials, alternating signs.`],
    [R`$1-\frac{x^2}{2!}+\frac{x^4}{4!}-\cdots$ is`, R`$\cos x$`, [R`$\sin x$`, R`$e^{-x^2}$`, R`$\frac{1}{1+x^2}$`], R`Even powers with factorials.`],
    [R`$x-\frac{x^2}{2}+\frac{x^3}{3}-\cdots$ is`, R`$\ln(1+x)$`, [R`$e^x-1$`, R`$\sin x$`, R`$\arctan x$`], R`Integrate $\frac{1}{1+x} = 1-x+x^2-\cdots$.`],
    [R`The first three nonzero terms of the Maclaurin series of $e^{-x^2}$ are`, R`$1-x^2+\frac{x^4}{2}$`, [R`$1-x^2+\frac{x^4}{4}$`, R`$1+x^2+\frac{x^4}{2}$`, R`$1-2x+2x^2$`], R`Substitute $-x^2$ into $1+u+\frac{u^2}{2}$.`],
    [R`In a Taylor series at $a$, the coefficient of $(x-a)^k$ is`, R`$\frac{f^{(k)}(a)}{k!}$`, [R`$f^{(k)}(a)$`, R`$\frac{f^{(k)}(0)}{k!}$`, R`$k!\,f^{(k)}(a)$`], R`Matching derivatives at $a$.`],
    [R`The Maclaurin series of $\sin\left(x^2\right)$ starts`, R`$x^2-\frac{x^6}{6}+\cdots$`, [R`$x^2-\frac{x^3}{6}+\cdots$`, R`$2x-\frac{x^6}{3}$`, R`$x-\frac{x^6}{6}$`], R`Replace $x$ with $x^2$ in $x-\frac{x^3}{6}$.`]
  ]),

  /* ---------------- power series ---------------- */
  cmc('power', { vars: { c: [2, 3, 4, 5] },
    prompt: R`What is the radius of convergence of $\displaystyle\sum_{k=0}^\infty\frac{x^k}{ {{c}}^k}$?`,
    answer: 'c', distractors: ['1 / c', '1', 'c * c', '0'], decimals: 4, format: '$R = {}$',
    explain: R`It is geometric with ratio $\frac{x}{ {{c}} }$, which needs $\left|\frac{x}{ {{c}} }\right|\lt1$: $|x|\lt{{c}}$.` }),
  calc('power', { vars: { c: [2, 3, 4, 5, 6], a: [1, 2, 3, 4] },
    prompt: R`Find the radius of convergence of $\displaystyle\sum_{k=1}^\infty\frac{(x-{{a}})^k}{k\cdot{{c}}^k}$.`,
    answer: 'c',
    explain: R`Ratio test: $\frac{|x-{{a}}|}{ {{c}} }\cdot\frac{k}{k+1}\to\frac{|x-{{a}}|}{ {{c}} }\lt1$, so $R = {{c}}$, centered at {{a}}.` }),
  calc('power', { vars: { c: [2, 3, 4, 5] },
    prompt: R`Using $\sum_{k=1}^\infty kx^k = \frac{x}{(1-x)^2}$, find $\displaystyle\sum_{k=1}^\infty\frac{k}{ {{c}}^k}$.`,
    answer: 'c / (c - 1)^2', decimals: 4,
    explain: R`Put $x = \frac{1}{ {{c}} }$: $\frac{1/{{c}}}{\left(1-1/{{c}}\right)^2} = \frac{ {{c}} }{ {{= (c-1)^2}} }\approx{{= answer | 4}}$.` }),
  calc('power', { vars: { c: [2, 3, 4] },
    prompt: R`Using $\sum_{k=1}^\infty\frac{x^k}{k} = -\ln(1-x)$, find $\displaystyle\sum_{k=1}^\infty\frac{1}{k\cdot{{c}}^k}$.`,
    answer: 'ln(c / (c - 1))', decimals: 4,
    explain: R`Put $x = \frac{1}{ {{c}} }$: $-\ln\left(1-\frac{1}{ {{c}} }\right) = \ln\frac{ {{c}} }{ {{= c-1}} }\approx{{= answer | 4}}$.` }),
  bank('power', [
    [R`The interval of convergence of $\sum\frac{x^k}{k}$ is`, R`$[-1,1)$`, [R`$(-1,1)$`, R`$[-1,1]$`, R`$(-1,1]$`], R`At $x = 1$: harmonic, diverges. At $x = -1$: alternating harmonic, converges.`],
    [R`The interval of convergence of $\sum\frac{x^k}{k^2}$ is`, R`$[-1,1]$`, [R`$(-1,1)$`, R`$[-1,1)$`, R`$(-1,1]$`], R`At both endpoints $\sum\frac{1}{k^2}$ converges (absolutely).`],
    [R`$\sum k!\,x^k$ converges`, R`only at $x = 0$`, [R`for all $x$`, R`for $|x|\lt1$`, R`for $|x|\le1$`], R`Ratio: $(k+1)|x|\to\infty$ unless $x = 0$.`],
    [R`$\sum\frac{x^k}{k!}$ converges`, R`for all real $x$`, [R`only at $x = 0$`, R`for $|x|\lt1$`, R`for $|x|\lt e$`], R`Ratio: $\frac{|x|}{k+1}\to0$. It is $e^x$.`],
    [R`$\sum(x+2)^k$ is centered at`, R`$x = -2$`, [R`$x = 2$`, R`$x = 0$`, R`$x = 1$`], R`$(x-a)^k$ with $a = -2$.`],
    [R`Differentiating a power series term by term`, R`keeps the same radius of convergence`, [R`doubles the radius`, R`can only shrink the radius to 0`, R`is never allowed`], R`The endpoints may change behavior, but $R$ does not.`],
    [R`After finding the radius with the ratio test, you must`, R`check each endpoint separately`, [R`stop: the endpoints always diverge`, R`stop: the endpoints always converge`, R`double the radius`], R`The ratio test gives $L = 1$ at the endpoints.`]
  ]),

  /* ---------------- Euler's formula ---------------- */
  calc('eulerformula', { vars: { m: [3, 4, 6], n: [2, 3, 4, 5] },
    prompt: R`Find the real part of $\left(\cos\frac{\pi}{ {{m}} }+i\sin\frac{\pi}{ {{m}} }\right)^{ {{n}} }$.`,
    answer: 'round(cos(n * pi / m), 4)',
    explain: R`De Moivre: the power is $\cos\frac{ {{n}}\pi}{ {{m}} }+i\sin\frac{ {{n}}\pi}{ {{m}} }$, with real part $\cos\frac{ {{n}}\pi}{ {{m}} }\approx{{= answer | 4}}$.` }),
  calc('eulerformula', { vars: { k: [1, 2, 3, 4, 5, 7, 8, 10, 11] },
    prompt: R`Find the imaginary part of $e^{i\cdot {{k}}\pi/6}$.`,
    answer: 'round(sin(k * pi / 6), 4)',
    explain: R`$e^{i\theta} = \cos\theta+i\sin\theta$, so the imaginary part is $\sin\frac{ {{k}}\pi}{6}\approx{{= answer | 4}}$.` }),
  calc('eulerformula', { vars: { it: [{ a: 3, b: 4 }, { a: 5, b: 12 }, { a: 6, b: 8 }, { a: 1, b: 1 }, { a: 2, b: 3 }] },
    prompt: R`Find the modulus $|z|$ of $z = {{a}}+{{b}}i$.`,
    answer: 'sqrt(a^2 + b^2)', decimals: 4,
    explain: R`$|z| = \sqrt{ {{a}}^2+{{b}}^2} = \sqrt{ {{= a^2 + b^2}} }\approx{{= answer | 4}}$.` }),
  bank('eulerformula', [
    [R`$e^{i\pi} =$`, R`$-1$`, ['1', R`$i$`, '0'], R`$\cos\pi+i\sin\pi = -1$.`],
    [R`$e^{i\pi/2} =$`, R`$i$`, [R`$-i$`, '1', '0'], R`$\cos\frac\pi2+i\sin\frac\pi2 = i$.`],
    [R`$|e^{i\theta}|$ for real $\theta$ is`, '1', [R`$\theta$`, R`$e^\theta$`, '0'], R`$\cos^2\theta+\sin^2\theta = 1$: it lies on the unit circle.`],
    [R`$\frac{e^{i\theta}+e^{-i\theta}}{2} =$`, R`$\cos\theta$`, [R`$\sin\theta$`, R`$i\sin\theta$`, R`$e^{\theta}$`], R`The sine parts cancel.`],
    [R`Euler's formula comes from`, R`substituting $x = i\theta$ into the Maclaurin series of $e^x$`, [R`integrating $\sin\theta$`, R`the quadratic formula`, R`Euler's method`], R`The real terms form $\cos\theta$ and the imaginary terms $i\sin\theta$.`],
    [R`Multiplying $r_1e^{i\alpha}$ by $r_2e^{i\beta}$ gives`, R`$r_1r_2\,e^{i(\alpha+\beta)}$`, [R`$(r_1+r_2)e^{i\alpha\beta}$`, R`$r_1r_2\,e^{i\alpha\beta}$`, R`$(r_1+r_2)e^{i(\alpha+\beta)}$`], R`Moduli multiply, angles add.`],
    [R`$i^3 =$`, R`$-i$`, [R`$i$`, '−1', '1'], R`$i^2 = -1$, so $i^3 = -i$.`]
  ]),

  /* ---------------- Fourier series ---------------- */
  calc('fourier', { vars: { n: [1, 3, 5, 7] },
    prompt: R`For the square wave $f(x) = -1$ on $(-\pi,0)$ and $1$ on $(0,\pi)$, with $b_n = \frac1\pi\int_{-\pi}^{\pi}f(x)\sin nx\,dx$, find $b_{ {{n}} }$.`,
    answer: '4 / (n * pi)', decimals: 4,
    explain: R`$f$ is odd, so $b_n = \frac2\pi\int_0^\pi\sin nx\,dx = \frac{2}{n\pi}(1-\cos n\pi)$. For odd $n$ this is $\frac{4}{n\pi}$: $b_{ {{n}} } = \frac{4}{ {{n}}\pi}\approx{{= answer | 4}}$.` }),
  calc('fourier', { vars: { n: [1, 2, 3, 4, 5] },
    prompt: R`For $f(x) = x$ on $[-\pi,\pi]$, with $b_n = \frac1\pi\int_{-\pi}^{\pi}x\sin nx\,dx$, find $b_{ {{n}} }$.`,
    answer: '2 * (-1)^(n + 1) / n', decimals: 4,
    explain: R`Parts gives $b_n = -\frac{2\cos n\pi}{n} = \frac{2(-1)^{n+1}}{n}$, so $b_{ {{n}} } = {{= answer | 4}}$.` }),
  calc('fourier', { vars: { n: [1, 2, 3, 4] },
    prompt: R`For $f(x) = x^2$ on $[-\pi,\pi]$, with $a_n = \frac1\pi\int_{-\pi}^{\pi}x^2\cos nx\,dx$, find $a_{ {{n}} }$.`,
    answer: '4 * (-1)^n / n^2', decimals: 4,
    explain: R`Parts twice: $\int_{-\pi}^{\pi}x^2\cos nx\,dx = \frac{4\pi(-1)^n}{n^2}$, so $a_{ {{n}} } = \frac{4(-1)^{ {{n}} } }{ {{= n^2}} } = {{= answer | 4}}$.` }),
  bank('fourier', [
    [R`The Fourier series of an odd function contains`, R`only sine terms`, [R`only cosine terms`, R`only the constant term`, R`both, always`], R`Every $a_n$ integrates an odd function over $[-\pi,\pi]$, giving 0.`],
    [R`The Fourier series of an even function contains`, R`only cosine terms (and the constant)`, [R`only sine terms`, R`no constant term`, R`only odd harmonics`], R`Every $b_n$ is 0.`],
    [R`At a jump discontinuity, a Fourier series converges to`, R`the average of the left and right limits`, [R`the left limit`, R`the right limit`, R`0`], R`It splits the difference.`],
    [R`$\int_{-\pi}^{\pi}\sin(2x)\sin(3x)\,dx =$`, '0', [R`$\pi$`, R`$2\pi$`, R`$\frac\pi2$`], R`Orthogonality: different frequencies integrate to 0.`],
    [R`$\int_{-\pi}^{\pi}\cos^2(4x)\,dx =$`, R`$\pi$`, ['0', R`$2\pi$`, R`$\frac\pi4$`], R`Same frequency: $\int\cos^2 nx = \pi$ over a full period.`],
    [R`With $f\sim\frac{a_0}{2}+\sum(a_n\cos nx+b_n\sin nx)$, the constant $\frac{a_0}{2}$ equals`, R`the average value of $f$ over $[-\pi,\pi]$`, [R`$f(0)$`, R`the maximum of $f$`, R`$b_1$`], R`$\frac{a_0}{2} = \frac{1}{2\pi}\int_{-\pi}^{\pi}f\,dx$.`],
    [R`Near a jump, partial sums of a Fourier series`, R`overshoot by a fixed amount (the Gibbs phenomenon)`, [R`match $f$ exactly`, R`are always 0`, R`diverge to infinity`], R`The overshoot narrows with more terms but does not vanish.`]
  ])
];

module.exports = { hint: 'Write down what the question gives you and which formula connects it to what you want.', topics, ladders, questions };
