#!/usr/bin/env node
/*
 * Downloads real product photos from msubookstore.org into images/products/
 * and writes assets/photos.js so the site shows them instead of illustrations.
 *
 *   node scripts/fetch-photos.cjs           # fetch photos that aren't downloaded yet
 *   node scripts/fetch-photos.cjs --force   # re-download everything
 *
 * Needs Node 18+ (built-in fetch). No npm install required.
 *
 * Products that only link to a category page have no single photo to grab. To add one by
 * hand, save it as images/products/<product id>.jpg (or .png/.webp) and rerun the script:
 * any image named after a product id is picked up automatically.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'images', 'products');
const PHOTOS_JS = path.join(ROOT, 'assets', 'photos.js');
const STORE = require(path.join(ROOT, 'assets', 'data.js'));
const ORIGIN = 'https://www.msubookstore.org';
const BASE = (process.env.STORE_BASE || ORIGIN).replace(/\/$/, ''); // override for testing
const FORCE = process.argv.includes('--force');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36';
const EXT = { 'image/jpeg': '.jpg', 'image/png': '.png', 'image/webp': '.webp', 'image/gif': '.gif', 'image/avif': '.avif' };

const sleep = ms => new Promise(r => setTimeout(r, ms));
const rebase = u => u.startsWith(ORIGIN) ? BASE + u.slice(ORIGIN.length) : u;
const decode = s => s.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/\\\//g, '/');

function existing(id) {
  return fs.readdirSync(OUT_DIR).find(f => path.parse(f).name === id && Object.values(EXT).includes(path.extname(f).toLowerCase()));
}

// Find the main product image in a product page's HTML.
function findImage(html, pageUrl) {
  const candidates = [];
  const meta = (attr, name) => {
    const re = new RegExp(`<meta[^>]+${attr}=["']${name}["'][^>]*>`, 'gi');
    for (const tag of html.match(re) || []) {
      const m = tag.match(/content=["']([^"']+)["']/i);
      if (m) candidates.push(m[1]);
    }
  };
  meta('property', 'og:image');
  meta('name', 'og:image');
  meta('name', 'twitter:image');
  meta('property', 'twitter:image');
  // JSON-LD product schema
  for (const block of html.match(/<script[^>]+application\/ld\+json[^>]*>[\s\S]*?<\/script>/gi) || []) {
    const m = block.match(/"image"\s*:\s*(?:\[\s*)?"([^"]+)"/);
    if (m) candidates.push(m[1]);
  }
  // common product gallery image paths
  for (const m of html.matchAll(/<img[^>]+(?:data-src|src)=["']([^"']+)["']/gi)) {
    if (/catalog\/product|\/images\/|\.ssp|resizeid|product/i.test(m[1]) && !/logo|placeholder|icon|sprite/i.test(m[1])) candidates.push(m[1]);
  }
  const url = candidates.map(decode).find(u => u && !/logo|placeholder/i.test(u));
  return url ? new URL(url, pageUrl).href : null;
}

async function get(url, accept) {
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: accept }, redirect: 'follow' });
      if (res.ok) return res;
      if (res.status === 404) throw new Error('404 not found');
      throw new Error(`HTTP ${res.status}`);
    } catch (err) {
      if (attempt === 3 || /404/.test(err.message)) throw err;
      await sleep(1000 * attempt);
    }
  }
}

async function fetchPhoto(p) {
  const pageUrl = rebase(p.url);
  const html = await (await get(pageUrl, 'text/html')).text();
  const imgUrl = findImage(html, pageUrl);
  if (!imgUrl) throw new Error('no product image found on page');
  const res = await get(rebase(imgUrl), 'image/*');
  const type = (res.headers.get('content-type') || '').split(';')[0].trim().toLowerCase();
  if (type && !type.startsWith('image/')) throw new Error(`image URL returned ${type}, not an image`);
  const ext = EXT[type] || path.extname(new URL(imgUrl).pathname).toLowerCase() || '.jpg';
  if (!Object.values(EXT).includes(ext)) throw new Error(`not an image (${type || 'unknown type'})`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 1000) throw new Error('image too small, probably a placeholder');
  for (const f of fs.readdirSync(OUT_DIR)) if (path.parse(f).name === p.id) fs.unlinkSync(path.join(OUT_DIR, f));
  const file = p.id + ext;
  fs.writeFileSync(path.join(OUT_DIR, file), buf);
  return file;
}

function writePhotosJs() {
  const ids = new Set(STORE.products.map(p => p.id));
  const map = {};
  for (const f of fs.readdirSync(OUT_DIR).sort()) {
    const { name, ext } = path.parse(f);
    if (ids.has(name) && Object.values(EXT).includes(ext.toLowerCase())) map[name] = `images/products/${f}`;
  }
  fs.writeFileSync(PHOTOS_JS,
    '/* Generated by scripts/fetch-photos.cjs. Maps product id -> local photo path.\n' +
    ' * Products without a photo show an illustration instead. */\n' +
    `window.PHOTOS = ${JSON.stringify(map, null, 2)};\n`);
  return Object.keys(map).length;
}

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const withPage = STORE.products.filter(p => /\/product\//.test(p.url));
  const noPage = STORE.products.filter(p => !/\/product\//.test(p.url));
  const todo = withPage.filter(p => FORCE || !existing(p.id));
  console.log(`${withPage.length} products have their own page, ${todo.length} to download.`);

  const failed = [];
  let i = 0;
  const worker = async () => {
    while (i < todo.length) {
      const p = todo[i++];
      try {
        const file = await fetchPhoto(p);
        console.log(`  ✓ ${p.name} → ${file}`);
      } catch (err) {
        failed.push(p);
        console.log(`  ✗ ${p.name}: ${err.message}`);
      }
      await sleep(400); // be polite to the store's server
    }
  };
  await Promise.all([worker(), worker(), worker()]);

  const count = writePhotosJs();
  console.log(`\nassets/photos.js now lists ${count} of ${STORE.products.length} products.`);
  const missing = [...failed, ...noPage.filter(p => !existing(p.id))];
  if (missing.length) {
    console.log(`\nStill using illustrations for ${missing.length} products. To add photos by hand, save them as:`);
    for (const p of missing) console.log(`  images/products/${p.id}.jpg   (${p.name})`);
    console.log('then run this script again.');
  }
})().catch(err => { console.error(err); process.exit(1); });
